receivers:
  prometheus:
    config:
      scrape_configs:
      - job_name: 'nodeexporter'
        scrape_interval: 60s
        static_configs:
        - targets:
          - '127.0.0.1:9100'

processors:
  resource:
    attributes:
    # Set `job` and `instance` resource attributes
    # to match up with what you would expect to see
    # in Prometheus server.
    - key: job
      action: upsert
      from_attribute: service.name
    - key: instance
      action: upsert
      from_attribute: service.instance.id
    # Google will consider metrics with `service.name` and
    # `service.instance.id` to be `generic_task` monitored
    # resource type. To get around this, and use `generic_node`,
    # delete the resource attributes.
    - key: service.name
      action: delete
    - key: service.instance.id
      action: delete

exporters: 
  googlecloud:

service:
  pipelines:
    metrics:
      receivers:
      - prometheus
      processors:
      - resource
      exporters:
      - googlecloud
