receivers:
  prometheus:
    config:
      scrape_configs:
      - job_name: 'nodeexporter'
        scrape_interval: 60s
        static_configs:
        - targets:
          - '127.0.0.1:9100'

exporters: 
  googlecloud:
    metric:
      prefix: workload.googleapis.com/nodeexporter

service:
  pipelines:
    metrics:
      receivers:
      - prometheus
      exporters:
      - googlecloud
