// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("qradar")
	ScopeName = "github.com/observiq/bindplane-otel-collector/exporter/qradar"
)

const (
	LogsStability = component.StabilityLevelAlpha
)
