.PHONY: clean
clean:
	rm -rf go-msi.exe config.yaml cinc-auditor.msi observiq-otel-collector.exe observiq-otel-collector.msi \
		opentelemetry-java-contrib-jmx-metrics.jar wix-binaries.zip wix.dynamic.json \
		wix plugins LICENSE VERSION.txt
