.PHONY: clean
clean:
	rm -rf go-msi.exe config.yaml cinc-auditor.msi bindplane-agent.exe bindplane-agent.msi \
		opentelemetry-java-contrib-jmx-metrics.jar wix-binaries.zip wix.dynamic.json \
		wix plugins LICENSE VERSION.txt
