// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	rollback "github.com/observiq/observiq-otel-collector/updater/internal/rollback"
	mock "github.com/stretchr/testify/mock"
)

// ActionAppender is an autogenerated mock type for the ActionAppender type
type ActionAppender struct {
	mock.Mock
}

// AppendAction provides a mock function with given fields: action
func (_m *ActionAppender) AppendAction(action rollback.RollbackableAction) {
	_m.Called(action)
}

type mockConstructorTestingTNewActionAppender interface {
	mock.TestingT
	Cleanup(func())
}

// NewActionAppender creates a new instance of ActionAppender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewActionAppender(t mockConstructorTestingTNewActionAppender) *ActionAppender {
	mock := &ActionAppender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
