// Code generated by mockery v2.28.1. DO NOT EDIT.

package mocks

import (
	action "github.com/observiq/observiq-otel-collector/updater/internal/action"
	mock "github.com/stretchr/testify/mock"
)

// MockRollbacker is an autogenerated mock type for the Rollbacker type
type MockRollbacker struct {
	mock.Mock
}

// AppendAction provides a mock function with given fields: _a0
func (_m *MockRollbacker) AppendAction(_a0 action.RollbackableAction) {
	_m.Called(_a0)
}

// Backup provides a mock function with given fields:
func (_m *MockRollbacker) Backup() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Rollback provides a mock function with given fields:
func (_m *MockRollbacker) Rollback() {
	_m.Called()
}

type mockConstructorTestingTNewMockRollbacker interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockRollbacker creates a new instance of MockRollbacker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockRollbacker(t mockConstructorTestingTNewMockRollbacker) *MockRollbacker {
	mock := &MockRollbacker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
