receivers:
  mongodb:
    hosts:
      - endpoint: localhost:27017

processors:
  resourcedetection:
    detectors: ["system"]
    system:
      hostname_sources: ["os"]

  normalizesums:

  batch:

exporters:
  prometheus:
    endpoint: "localhost:9000"
    resource_to_telemetry_conversion:
      enabled: true

service:
  pipelines:
    metrics:
      receivers:
      - mongodb
      processors:
      - resourcedetection
      - normalizesums
      - batch
      exporters:
      - prometheus
