receivers:
  redis:
    endpoint: "localhost:6379"
    collection_interval: 60s

processors:
  resourcedetection:
    detectors: ["system"]
    system:
      hostname_sources: ["os"]

  batch:

exporters:
  prometheus:
    endpoint: "localhost:9000"
    resource_to_telemetry_conversion:
      enabled: true

service:
  pipelines:
    metrics:
      receivers:
        - redis
      processors:
        - resourcedetection
        - batch
      exporters:
        - prometheus
