receivers:
  hostmetrics:
    collection_interval: 60s
    scrapers:
      cpu:
      disk:
      load:
      filesystem:
      memory:
      network:
      paging:
      processes:

      # Uncomment "process" and "mute_process_name_error" to enable
      # per process metrics for cpu, memory, and disk.
      # This feature requires root / Administrative privileges.
      #process:
      #  mute_process_name_error: true

exporters: 
  # observIQ collector wraps the upstream Google Cloud exporter
  # with the following processors:
  #   - resource detection processor
  #   - resource attributes transposer processor
  #   - normalizesums processor
  #   - batch processor
  #
  # In additon to wrapping processors, the following settings are configured:
  #   - retry_on_failure.enabled: false
  #   - metric.prefix: workload.googleapis.com
  #   - resource mapping: default to generic_node monitored resource type.
  #     - node_id: host.name
  #     - namespace: host.name
  #     - location: global
  googlecloud:

service:
  pipelines:
    metrics:
      receivers:
      - hostmetrics
      exporters:
      - googlecloud
