receivers:
  hostmetrics:
    collection_interval: 60s
    scrapers:
      cpu:
      disk:
      load:
      filesystem:
      memory:
      network:
      paging:
      processes:

      # Uncomment "process" and "mute_process_name_error" to enable
      # per process metrics for cpu, memory, and disk.
      # This feature requires root / Administrative privileges.
      #process:
      #  mute_process_name_error: true

exporters: 
  googlecloud:

service:
  pipelines:
    metrics:
      receivers:
      - hostmetrics
      exporters:
      - googlecloud
