version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # Opentelemetry updates will be done manually
      - dependency-name: "github.com/open-telemetry/opentelemetry-collector*"
      - dependency-name: "go.opentelemetry.io/*"
      - dependency-name: "github.com/open-telemetry/opamp-go"
    commit-message:
      prefix: "deps"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/processor/resourceattributetransposerprocessor"
    schedule:
      interval: "weekly"
    ignore:
      # Opentelemetry updates will be done manually
      - dependency-name: "github.com/open-telemetry/opentelemetry-collector*"
      - dependency-name: "go.opentelemetry.io/*"
  - package-ecosystem: "gomod"
    directory: "/processor/throughputmeasurementprocessor/"
    schedule:
      interval: "weekly"
    ignore:
      # Opentelemetry updates will be done manually
      - dependency-name: "github.com/open-telemetry/opentelemetry-collector*"
      - dependency-name: "go.opentelemetry.io/*"
    commit-message:
      prefix: "deps"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/processor/samplingprocessor/"
    schedule:
      interval: "weekly"
    ignore:
      # Opentelemetry updates will be done manually
      - dependency-name: "github.com/open-telemetry/opentelemetry-collector*"
      - dependency-name: "go.opentelemetry.io/*"
    commit-message:
      prefix: "deps"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/processor/logcountprocessor/"
    schedule:
      interval: "weekly"
    ignore:
      # Opentelemetry updates will be done manually
      - dependency-name: "github.com/open-telemetry/opentelemetry-collector*"
      - dependency-name: "go.opentelemetry.io/*"
    commit-message:
      prefix: "deps"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/processor/logdeduplicationprocessor//"
    schedule:
      interval: "weekly"
    ignore:
      # Opentelemetry updates will be done manually
      - dependency-name: "github.com/open-telemetry/opentelemetry-collector*"
      - dependency-name: "go.opentelemetry.io/*"
    commit-message:
      prefix: "deps"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/processor/maskprocessor/"
    schedule:
      interval: "weekly"
    ignore:
      # Opentelemetry updates will be done manually
      - dependency-name: "github.com/open-telemetry/opentelemetry-collector*"
      - dependency-name: "go.opentelemetry.io/*"
    commit-message:
      prefix: "deps"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/processor/metricextractprocessor/"
    schedule:
      interval: "weekly"
    ignore:
      # Opentelemetry updates will be done manually
      - dependency-name: "github.com/open-telemetry/opentelemetry-collector*"
      - dependency-name: "go.opentelemetry.io/*"
    commit-message:
      prefix: "deps"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/processor/datapointcountprocessor/"
    schedule:
      interval: "weekly"
    ignore:
      # Opentelemetry updates will be done manually
      - dependency-name: "github.com/open-telemetry/opentelemetry-collector*"
      - dependency-name: "go.opentelemetry.io/*"
    commit-message:
      prefix: "deps"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/processor/spancountprocessor/"
    schedule:
      interval: "weekly"
    ignore:
      # Opentelemetry updates will be done manually
      - dependency-name: "github.com/open-telemetry/opentelemetry-collector*"
      - dependency-name: "go.opentelemetry.io/*"
    commit-message:
      prefix: "deps"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/processor/metricstatsprocessor/"
    schedule:
      interval: "weekly"
    ignore:
      # Opentelemetry updates will be done manually
      - dependency-name: "github.com/open-telemetry/opentelemetry-collector*"
      - dependency-name: "go.opentelemetry.io/*"
    commit-message:
      prefix: "deps"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/receiver/sapnetweaverreceiver"
    schedule:
      interval: "weekly"
    ignore:
      # Opentelemetry updates will be done manually
      - dependency-name: "go.opentelemetry.io/*"
      - dependency-name: "github.com/open-telemetry/opentelemetry-collector*"
    commit-message:
      prefix: "deps"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/receiver/azureblobrehydrationreceiver"
    schedule:
      interval: "weekly"
    ignore:
      # Opentelemetry updates will be done manually
      - dependency-name: "go.opentelemetry.io/*"
      - dependency-name: "github.com/open-telemetry/opentelemetry-collector*"
    commit-message:
      prefix: "deps"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/receiver/httpreceiver"
    schedule:
      interval: "weekly"
    ignore:
      # Opentelemetry updates will be done manually
      - dependency-name: "go.opentelemetry.io/*"
      - dependency-name: "github.com/open-telemetry/opentelemetry-collector*"
    commit-message:
      prefix: "deps"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/receiver/m365receiver"
    schedule:
      interval: "weekly"
    ignore:
      # Opentelemetry updates will be done manually
      - dependency-name: "go.opentelemetry.io/*"
      - dependency-name: "github.com/open-telemetry/opentelemetry-collector*"
    commit-message:
      prefix: "deps"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "processor/removeemptyvaluesprocessor/"
    schedule:
      interval: "weekly"
    ignore:
      # Opentelemetry updates will be done manually
      - dependency-name: "github.com/open-telemetry/opentelemetry-collector*"
      - dependency-name: "go.opentelemetry.io/*"
    commit-message:
      prefix: "deps"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/receiver/pluginreceiver"
    schedule:
      interval: "weekly"
    ignore:
      # Opentelemetry updates will be done manually
      - dependency-name: "go.opentelemetry.io/*"
      - dependency-name: "github.com/open-telemetry/opentelemetry-collector*"
    commit-message:
      prefix: "deps"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/receiver/routereceiver"
    schedule:
      interval: "weekly"
    ignore:
      # Opentelemetry updates will be done manually
      - dependency-name: "go.opentelemetry.io/*"
      - dependency-name: "github.com/open-telemetry/opentelemetry-collector*"
    commit-message:
      prefix: "deps"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/exporter/googlecloudexporter"
    schedule:
      interval: "weekly"
    ignore:
      # Opentelemetry updates will be done manually
      - dependency-name: "github.com/open-telemetry/opentelemetry-collector*"
      - dependency-name: "go.opentelemetry.io/*"
    commit-message:
      prefix: "deps"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/exporter/chronicleexporter"
    schedule:
      interval: "weekly"
    ignore:
      # Opentelemetry updates will be done manually
      - dependency-name: "github.com/open-telemetry/opentelemetry-collector*"
      - dependency-name: "go.opentelemetry.io/*"
    commit-message:
      prefix: "deps"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/exporter/googlemanagedprometheusexporter"
    schedule:
      interval: "weekly"
    ignore:
      # Opentelemetry updates will be done manually
      - dependency-name: "github.com/open-telemetry/opentelemetry-collector*"
      - dependency-name: "go.opentelemetry.io/*"
    commit-message:
      prefix: "deps"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/exporter/azureblobexporter"
    schedule:
      interval: "weekly"
    ignore:
      # Opentelemetry updates will be done manually
      - dependency-name: "github.com/open-telemetry/opentelemetry-collector*"
      - dependency-name: "go.opentelemetry.io/*"
    commit-message:
      prefix: "deps"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/exporter/snowflakeexporter"
    schedule:
      interval: "weekly"
    ignore:
      # Opentelemetry updates will be done manually
      - dependency-name: "github.com/open-telemetry/opentelemetry-collector*"
      - dependency-name: "go.opentelemetry.io/*"
    commit-message:
      prefix: "deps"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/expr"
    schedule:
      interval: "weekly"
    ignore:
      # Opentelemetry updates will be done manually
      - dependency-name: "github.com/open-telemetry/opentelemetry-collector*"
      - dependency-name: "go.opentelemetry.io/*"
    commit-message:
      prefix: "deps"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/updater"
    schedule:
      interval: "weekly"
    ignore:
      # Opentelemetry updates will be done manually
      - dependency-name: "github.com/open-telemetry/opamp-go"
    commit-message:
      prefix: "deps"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/packagestate"
    schedule:
      interval: "weekly"
    ignore:
      # Opentelemetry updates will be done manually
      - dependency-name: "github.com/open-telemetry/opamp-go"
    commit-message:
      prefix: "deps"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/receiver/telemetrygeneratorreceiver"
    schedule:
      interval: "weekly"
    ignore:
      # Opentelemetry updates will be done manually
      - dependency-name: "go.opentelemetry.io/*"
      - dependency-name: "github.com/open-telemetry/opentelemetry-collector*"
    commit-message:
      prefix: "deps"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/extension/bindplaneextension"
    schedule:
      interval: "weekly"
    ignore:
      # Opentelemetry updates will be done manually
      - dependency-name: "go.opentelemetry.io/*"
      - dependency-name: "github.com/open-telemetry/opentelemetry-collector*"
    commit-message:
      prefix: "deps"
      include: "scope"
