version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # Opentelemetry updates will be done manually
      - dependency-name: "github.com/open-telemetry/opentelemetry-collector*"
      - dependency-name: "go.opentelemetry.io/collector/*"
    commit-message:
      prefix: "deps"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/processor/resourceattributetransposerprocessor"
    schedule:
      interval: "weekly"
    ignore:
      # Opentelemetry updates will be done manually
      - dependency-name: "github.com/open-telemetry/opentelemetry-collector*"
      - dependency-name: "go.opentelemetry.io/collector/*"
    commit-message:
      prefix: "deps"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/receiver/pluginreceiver"
    schedule:
      interval: "weekly"
    ignore:
      # Opentelemetry updates will be done manually
      - dependency-name: "go.opentelemetry.io/collector/*"
    commit-message:
      prefix: "deps"
      include: "scope"
