# This example showcases filelog + json parser's ability to parse abitrary json.
receivers:
  filelog:
    include:
    # app represents a custom application using json logging
    - /var/log/app/log.json
    start_at: end
    resource:
      log_type: app
    operators:
      - type: json_parser

exporters: 
  googlecloud:
    retry_on_failure:
      enabled: false
    project: REPLACE_ME

service:
  pipelines:
    logs:
      receivers:
      - filelog
      exporters:
      - googlecloud
