# This example uses Redis to showcase filelog + regex.
receivers:
  filelog:
    include:
    - /var/log/redis/redis.log
    start_at: end
    resource:
      log_type: redis
    operators:
      - type: regex_parser
        regex: '^\[?(?P<pid>\d+):?(?P<role>[A-Z])?\]?\s+(?P<timestamp>\d{2}\s+\w+(?:\s+\d{4})?\s+\d{2}:\d{2}:\d{2}.\d{3})\s+(?P<level>[\*|#|\-|\.])\s+(?P<message>.*)'
        # Regex will parse the severity value to attributes.level, which can
        # then be mapped to the log entry's top level severity field
        severity:
          parse_from: attributes.level
          mapping:
            warn: '#'
            info: '-'
            debug: ','
            info2: '*'

exporters: 
  googlecloud:

service:
  pipelines:
    logs:
      receivers:
      - filelog
      exporters:
      - googlecloud
