receivers:
  filelog:
    include:
    - /var/log/messages
    start_at: end

exporters: 
  googlecloud:

service:
  pipelines:
    logs:
      receivers:
      - filelog
      exporters:
      - googlecloud
