// Code generated by mockery v2.42.0. DO NOT EDIT.

package chronicleexporter

import (
	context "context"

	generated "github.com/observiq/bindplane-agent/exporter/chronicleexporter/protos/generated"
	mock "github.com/stretchr/testify/mock"

	plog "go.opentelemetry.io/collector/pdata/plog"
)

// MockMarshaler is an autogenerated mock type for the logMarshaler type
type MockMarshaler struct {
	mock.Mock
}

// MarshalRawLogs provides a mock function with given fields: ctx, ld
func (_m *MockMarshaler) MarshalRawLogs(ctx context.Context, ld plog.Logs) ([]*generated.BatchCreateLogsRequest, error) {
	ret := _m.Called(ctx, ld)

	if len(ret) == 0 {
		panic("no return value specified for MarshalRawLogs")
	}

	var r0 []*generated.BatchCreateLogsRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, plog.Logs) ([]*generated.BatchCreateLogsRequest, error)); ok {
		return rf(ctx, ld)
	}
	if rf, ok := ret.Get(0).(func(context.Context, plog.Logs) []*generated.BatchCreateLogsRequest); ok {
		r0 = rf(ctx, ld)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*generated.BatchCreateLogsRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, plog.Logs) error); ok {
		r1 = rf(ctx, ld)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockMarshaler creates a new instance of MockMarshaler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMarshaler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMarshaler {
	mock := &MockMarshaler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
