receivers:
  bigip:
    username: $BIGIP_USERNAME
    password: $BIGIP_USERNAME
    collection_interval: 60s
    # Update the IP address to point to your Big IP iControl REST API.
    endpoint: https://127.0.0.1:443
    tls:
      insecure_skip_verify: true

exporters:
  googlecloud:
    metric:
      resource_filters:
        - prefix: bigip

service:
  pipelines:
    metrics:
      receivers:
        - bigip
      exporters:
        - googlecloud
