---
linters:
  enable:
    - bodyclose
    - goconst
    - gocritic
    - goimports
    - maligned
    - misspell
    - nakedret
    - prealloc
    - unconvert
    - unparam
    - whitespace
    - ineffassign
