before:
  hooks:
    - make release-prep

# https://goreleaser.com/customization/build/
builds:
  - id: collector
    binary: observiq-collector
    main: ./cmd/collector
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/observiq/observiq-collector/internal/version.version=v{{ .Version }}
      - -X github.com/observiq/observiq-collector/internal/version.gitHash={{ .FullCommit }}
      - -X github.com/observiq/observiq-collector/internal/version.date={{ .Date }}
    no_unique_dist_dir: false

# https://goreleaser.com/customization/archive/
archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    files:
      - LICENSE
      - src: release_deps/opentelemetry-java-contrib-jmx-metrics.jar
        dst: "."
        strip_parent: true
      - src: release_deps/config.yaml
        dst: "."
        strip_parent: true
      - src: release_deps/plugins/*
        dst: plugins
        strip_parent: true

    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - id: collector
    package_name: observiq-collector
    vendor: observIQ, Inc
    description: observIQ's distribution of the OpenTelemetry collector
    homepage: https://observiq.com/
    license: Apache 2.0
    formats:
    - rpm
    - deb
    bindir: /usr/bin
    contents:
    - src: release_deps/plugins
      dst: /opt/observiq-collector/plugins
      file_info:
        mode: 0774
        owner: observiq-collector
        group: observiq-collector
    - src: release_deps/config.yaml
      dst: /opt/observiq-collector/config.yaml
      file_info:
        mode: 0660
        owner: observiq-collector
        group: observiq-collector
      type: config|noreplace
    - src: release_deps/opentelemetry-java-contrib-jmx-metrics.jar
      dst: /opt/observiq-collector/opentelemetry-java-contrib-jmx-metrics.jar
      file_info:
        mode: 0550
        owner: observiq-collector
        group: observiq-collector
    scripts:
      preinstall: "./scripts/package/preinstall.sh"
      postinstall: ./scripts/package/postinstall.sh
# https://goreleaser.com/customization/checksum/
checksum:
  name_template: "{{ .ProjectName }}-v{{ .Version }}-SHA256SUMS"
  algorithm: sha256

# https://goreleaser.com/customization/sign/
signs:
  - cmd: cosign
    stdin: "{{ .Env.COSIGN_PWD }}"
    args:
      ["sign-blob", "--key=cosign.key", "--output=${signature}", "${artifact}"]
    artifacts: all

# https://goreleaser.com/customization/release/
release:
  draft: false
  extra_files:
    - glob: "./observiq-collector-*.msi"

# https://goreleaser.com/customization/changelog/
changelog:
  skip: false
  use: github
  sort: asc
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug Fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: "Dependencies"
      regexp: "^.*deps[(\\w)]*:+.*$"
      order: 30
    - title: Other
      order: 999
