project_name: observiq-otel-collector

before:
  hooks:
    - make release-prep CURR_VERSION={{ .Version }}

# https://goreleaser.com/customization/build/
builds:
  - id: collector
    binary: observiq-otel-collector
    main: ./cmd/collector
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/observiq/observiq-otel-collector/internal/version.version=v{{ .Version }}
      - -X github.com/observiq/observiq-otel-collector/internal/version.gitHash={{ .FullCommit }}
      - -X github.com/observiq/observiq-otel-collector/internal/version.date={{ .Date }}
    no_unique_dist_dir: false

# https://goreleaser.com/customization/archive/
archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    files:
      - LICENSE
      - src: release_deps/opentelemetry-java-contrib-jmx-metrics.jar
        dst: "."
        strip_parent: true
      - src: release_deps/config.yaml
        dst: "."
        strip_parent: true
      - src: release_deps/logging.yaml
        dst: "."
        strip_parent: true
      - src: release_deps/plugins/*
        dst: plugins
        strip_parent: true
      - src: release_deps/VERSION.txt
        dst: "."
        strip_parent: true

    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - id: collector
    file_name_template: "{{ .PackageName }}_{{ .Os }}_{{ .Arch }}"
    package_name: observiq-otel-collector
    vendor: observIQ, Inc
    maintainer: observIQ <support@observiq.com>
    description: observIQ's distribution of the OpenTelemetry collector
    homepage: https://github.com/observIQ/observiq-otel-collector
    license: Apache 2.0
    formats:
      - rpm
      - deb
    bindir: /opt/observiq-otel-collector
    contents:
      - dst: /opt/observiq-otel-collector
        type: dir
        file_info:
          mode: 0755
          owner: observiq-otel-collector
          group: observiq-otel-collector
      - src: release_deps/config.yaml
        dst: /opt/observiq-otel-collector/config.yaml
        file_info:
          mode: 0640
          owner: observiq-otel-collector
          group: observiq-otel-collector
        type: config|noreplace
      - src: release_deps/logging.yaml
        dst: /opt/observiq-otel-collector/logging.yaml
        file_info:
          mode: 0640
          owner: observiq-otel-collector
          group: observiq-otel-collector
        type: config|noreplace
      - src: LICENSE
        dst: /opt/observiq-otel-collector/LICENSE
        file_info:
          mode: 0644
          owner: observiq-otel-collector
          group: observiq-otel-collector
      - src: release_deps/VERSION.txt
        dst: /opt/observiq-otel-collector/VERSION.txt
        file_info:
          mode: 0644
          owner: observiq-otel-collector
          group: observiq-otel-collector
      - src: release_deps/opentelemetry-java-contrib-jmx-metrics.jar
        dst: /opt/opentelemetry-java-contrib-jmx-metrics.jar
        file_info:
          mode: 0755
          owner: observiq-otel-collector
          group: observiq-otel-collector
      - dst: /opt/observiq-otel-collector/plugins
        type: dir
        file_info:
          mode: 0750 # restrict plugins to owner / group only
          owner: observiq-otel-collector
          group: observiq-otel-collector
      # Note: plugins owner/group/mode is set in the post-install script
      # Attempting to set the permissions here results in the following error:
      # nfpm failed: cannot write header of release_deps/plugins/amazon_eks.yaml to data.tar.gz: archive/tar: missed writing 1736 bytes
      - src: release_deps/plugins/*
        dst: /opt/observiq-otel-collector/plugins
      # Storage dir is used by stateful receivers, such as filelog receiver. It allows
      # receivers to track their progress and buffer data.
      - dst: /opt/observiq-otel-collector/storage
        type: dir
        file_info:
          mode: 0750
          owner: observiq-otel-collector
          group: observiq-otel-collector
      - dst: /opt/observiq-otel-collector/log
        type: dir
        file_info:
          mode: 0750
          owner: observiq-otel-collector
          group: observiq-otel-collector
      - src: scripts/package/service/systemd/observiq-otel-collector.service
        dst: /usr/lib/systemd/system/observiq-otel-collector.service
        type: config
        file_info:
          mode: 0644
          owner: root
          group: root
    scripts:
      preinstall: ./scripts/package/preinstall.sh
      postinstall: ./scripts/package/postinstall.sh

# Build container images with docker buildx (mutli arch builds)
dockers:
  - goos: linux
    goarch: amd64
    ids:
      - collector
    image_templates:
      - "observiq/observiq-otel-collector-amd64:latest"
      - "observiq/observiq-otel-collector-amd64:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "observiq/observiq-otel-collector-amd64:{{ .Major }}.{{ .Minor }}"
      - "observiq/observiq-otel-collector-amd64:{{ .Major }}"
    dockerfile: ./Dockerfile
    use: buildx
    build_flag_templates:
      - "--label=created={{.Date}}"
      - "--label=title={{.ProjectName}}"
      - "--label=revision={{.FullCommit}}"
      - "--label=version={{.Version}}"
      - "--platform=linux/amd64"
    extra_files:
      - plugins
  - goos: linux
    goarch: arm64
    ids:
      - collector
    image_templates:
      - "observiq/observiq-otel-collector-arm64:latest"
      - "observiq/observiq-otel-collector-arm64:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "observiq/observiq-otel-collector-arm64:{{ .Major }}.{{ .Minor }}"
      - "observiq/observiq-otel-collector-arm64:{{ .Major }}"
    dockerfile: ./Dockerfile
    use: buildx
    build_flag_templates:
      - "--label=created={{.Date}}"
      - "--label=title={{.ProjectName}}"
      - "--label=revision={{.FullCommit}}"
      - "--label=version={{.Version}}"
      - "--platform=linux/arm64"
    extra_files:
      - plugins

docker_manifests:
  - name_template: "observiq/observiq-otel-collector:latest"
    image_templates:
      - "observiq/observiq-otel-collector-amd64:latest"
      - "observiq/observiq-otel-collector-arm64:latest"
    skip_push: false
  - name_template: "observiq/observiq-otel-collector:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    image_templates:
      - "observiq/observiq-otel-collector-amd64:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "observiq/observiq-otel-collector-arm64:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    skip_push: false
  - name_template: "observiq/observiq-otel-collector:{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "observiq/observiq-otel-collector-amd64:{{ .Major }}.{{ .Minor }}"
      - "observiq/observiq-otel-collector-arm64:{{ .Major }}.{{ .Minor }}"
    skip_push: false
  - name_template: "observiq/observiq-otel-collector:{{ .Major }}"
    image_templates:
      - "observiq/observiq-otel-collector-amd64:{{ .Major }}"
      - "observiq/observiq-otel-collector-arm64:{{ .Major }}"
    skip_push: false

# https://goreleaser.com/customization/checksum/
checksum:
  name_template: "{{ .ProjectName }}-v{{ .Version }}-SHA256SUMS"
  algorithm: sha256

# https://goreleaser.com/customization/sign/
signs:
  - cmd: cosign
    stdin: "{{ .Env.COSIGN_PWD }}"
    args:
      ["sign-blob", "--key=cosign.key", "--output=${signature}", "${artifact}"]
    artifacts: all

# https://goreleaser.com/customization/release/
release:
  draft: false

  # publish to a prerelease first
  prerelease: "true"
  extra_files:
    - glob: "./observiq-otel-collector*.msi"
    - glob: "./scripts/install/install_unix.sh"
    - glob: "./scripts/install/install_macos.sh"

# https://goreleaser.com/customization/changelog/
changelog:
  skip: false
  use: github
  sort: asc
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug Fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: "Dependencies"
      regexp: "^.*deps[(\\w)]*:+.*$"
      order: 30
    - title: Other
      order: 999

# https://goreleaser.com/customization/homebrew/
brews:
  - name: observiq-otel-collector@{{ .Major }}.{{ .Minor }}.{{ .Patch }}
    description: "observIQ's distribution of the OpenTelemetry Collector"
    tap:
      owner: observIQ
      name: homebrew-observiq-otel-collector
      branch: main
    download_strategy: CurlDownloadStrategy
    folder: Formula
    url_template: https://github.com/observIQ/observiq-otel-collector/releases/download/{{ .Tag }}/{{ .ArtifactName }}
    commit_author:
      name: observiq
      email: support@observiq.com
    homepage: "https://github.com/observIQ/observiq-otel-collector"
    license: "Apache 2.0"
    caveats: |
      ****************************************************************
      The configuration file that is run by the service is located at #{prefix}/config.yaml.

      If you are configuring a logreceiver the plugin directory is located at #{prefix}/plugins.
      ****************************************************************

      ****************************************************************
      Below are services commands to run to manage the collector service.
      If you wish to run the collector at boot prefix these commands with sudo
      otherwise the service will run at login.

      To start the collector service run:

        brew services start observiq/observiq-otel-collector/observiq-otel-collector@{{ .Major }}.{{ .Minor }}.{{ .Patch }}

      To stop the collector service run:

        brew services stop observiq/observiq-otel-collector/observiq-otel-collector@{{ .Major }}.{{ .Minor }}.{{ .Patch }}

      To restart the collector service run:

        brew services restart observiq/observiq-otel-collector/observiq-otel-collector@{{ .Major }}.{{ .Minor }}.{{ .Patch }}
      ****************************************************************

      ****************************************************************
      To uninstall the collector and its dependencies run the following commands:

          brew services stop observiq/observiq-otel-collector/observiq-otel-collector@{{ .Major }}.{{ .Minor }}.{{ .Patch }}
          brew uninstall observiq/observiq-otel-collector/observiq-otel-collector@{{ .Major }}.{{ .Minor }}.{{ .Patch }}

          # If you moved the opentelemetry-java-contrib-jmx-metrics.jar
          sudo rm /opt/opentelemetry-java-contrib-jmx-metrics.jar

      ****************************************************************
    install: |
      bin.install "observiq-otel-collector"
      prefix.install "LICENSE", "VERSION.txt", "logging.yaml"
      etc.install "config.yaml" => "observiq_config.yaml"
      prefix.install_symlink etc/"observiq_config.yaml" => "config.yaml"
      prefix.install Dir["plugins"]
      lib.install "opentelemetry-java-contrib-jmx-metrics.jar"
    service: |
      run [opt_bin/"observiq-otel-collector", "--config", opt_prefix/"config.yaml", "--logging", opt_prefix/"logging.yaml", "--manager", opt_prefix/"manager.yaml"]
      environment_variables OIQ_OTEL_COLLECTOR_HOME: opt_prefix
      keep_alive true
    # For local testing
    # skip_upload: "true"
