project_name: observiq-otel-collector

before:
  hooks:
    - make release-prep CURR_VERSION={{ .Version }}

# https://goreleaser.com/customization/build/
builds:
  - id: collector
    binary: observiq-otel-collector
    main: ./cmd/collector
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
      - "386"
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: linux
        goarch: "386"
      - goos: darwin
        goarch: "386"
    ldflags:
      - -s -w
      - -X github.com/observiq/observiq-otel-collector/internal/version.version=v{{ .Version }}
      - -X github.com/observiq/observiq-otel-collector/internal/version.gitHash={{ .FullCommit }}
      - -X github.com/observiq/observiq-otel-collector/internal/version.date={{ .Date }}
    no_unique_dist_dir: false
  - id: updater
    binary: updater
    dir: ./updater/
    main: ./cmd/updater
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
      - "386"
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: linux
        goarch: "386"
      - goos: darwin
        goarch: "386"
    ldflags:
      - -s -w
      - -X github.com/observiq/observiq-otel-collector/updater/internal/version.version=v{{ .Version }}
      - -X github.com/observiq/observiq-otel-collector/updater/internal/version.gitHash={{ .FullCommit }}
      - -X github.com/observiq/observiq-otel-collector/updater/internal/version.date={{ .Date }}
    no_unique_dist_dir: false

# https://goreleaser.com/customization/archive/
archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    files:
      - LICENSE
      - src: release_deps/opentelemetry-java-contrib-jmx-metrics.jar
        dst: "."
        strip_parent: true
      - src: release_deps/config.yaml
        dst: "."
        strip_parent: true
      - src: release_deps/logging.yaml
        dst: "."
        strip_parent: true
      - src: release_deps/plugins/*
        dst: plugins
        strip_parent: true
      - src: release_deps/VERSION.txt
        dst: "."
        strip_parent: true
      - src: release_deps/com.observiq.collector.plist
        dst: "install"
        strip_parent: true
      - src: release_deps/windows_service.json
        dst: install
        strip_parent: true
      - src: release_deps/observiq-otel-collector.service
        dst: "install"
        strip_parent: true
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - id: collector
    file_name_template: "{{ .PackageName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    package_name: observiq-otel-collector
    vendor: observIQ, Inc
    maintainer: observIQ <support@observiq.com>
    description: observIQ's distribution of the OpenTelemetry collector
    homepage: https://github.com/observIQ/observiq-otel-collector
    license: Apache 2.0
    formats:
      - rpm
      - deb
    bindir: /opt/observiq-otel-collector
    contents:
      - dst: /opt/observiq-otel-collector
        type: dir
        file_info:
          mode: 0755
          owner: observiq-otel-collector
          group: observiq-otel-collector
      - src: release_deps/config.yaml
        dst: /opt/observiq-otel-collector/config.yaml
        file_info:
          mode: 0640
          owner: observiq-otel-collector
          group: observiq-otel-collector
        type: config|noreplace
      - src: release_deps/logging.yaml
        dst: /opt/observiq-otel-collector/logging.yaml
        file_info:
          mode: 0640
          owner: observiq-otel-collector
          group: observiq-otel-collector
        type: config|noreplace
      - src: LICENSE
        dst: /opt/observiq-otel-collector/LICENSE
        file_info:
          mode: 0644
          owner: observiq-otel-collector
          group: observiq-otel-collector
      - src: release_deps/VERSION.txt
        dst: /opt/observiq-otel-collector/VERSION.txt
        file_info:
          mode: 0644
          owner: observiq-otel-collector
          group: observiq-otel-collector
      - src: release_deps/opentelemetry-java-contrib-jmx-metrics.jar
        dst: /opt/opentelemetry-java-contrib-jmx-metrics.jar
        file_info:
          mode: 0755
          owner: observiq-otel-collector
          group: observiq-otel-collector
      - dst: /opt/observiq-otel-collector/plugins
        type: dir
        file_info:
          mode: 0750 # restrict plugins to owner / group only
          owner: observiq-otel-collector
          group: observiq-otel-collector
      # Note: plugins owner/group/mode is set in the post-install script
      # Attempting to set the permissions here results in the following error:
      # nfpm failed: cannot write header of release_deps/plugins/amazon_eks.yaml to data.tar.gz: archive/tar: missed writing 1736 bytes
      - src: release_deps/plugins/*
        dst: /opt/observiq-otel-collector/plugins
      # Storage dir is used by stateful receivers, such as filelog receiver. It allows
      # receivers to track their progress and buffer data.
      - dst: /opt/observiq-otel-collector/storage
        type: dir
        file_info:
          mode: 0750
          owner: observiq-otel-collector
          group: observiq-otel-collector
      - dst: /opt/observiq-otel-collector/log
        type: dir
        file_info:
          mode: 0750
          owner: observiq-otel-collector
          group: observiq-otel-collector
      - src: service/observiq-otel-collector.service
        dst: /usr/lib/systemd/system/observiq-otel-collector.service
        type: config|noreplace
        file_info:
          mode: 0644
          owner: root
          group: root
    scripts:
      preinstall: ./scripts/package/preinstall.sh
      postinstall: ./scripts/package/postinstall.sh

# Build container images with docker buildx (mutli arch builds).
dockers:
  - id: ubuntu-amd64
    goos: linux
    goarch: amd64
    ids:
      - collector
    image_templates:
      - "observiq/observiq-otel-collector-amd64:latest"
      - "observiq/observiq-otel-collector-amd64:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "observiq/observiq-otel-collector-amd64:{{ .Major }}.{{ .Minor }}"
      - "observiq/observiq-otel-collector-amd64:{{ .Major }}"
      - "ghcr.io/observiq/observiq-otel-collector-amd64:latest"
      - "ghcr.io/observiq/observiq-otel-collector-amd64:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "ghcr.io/observiq/observiq-otel-collector-amd64:{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/observiq/observiq-otel-collector-amd64:{{ .Major }}"
      - "us-central1-docker.pkg.dev/observiq-containers/collector/observiq-otel-collector-amd64:latest"
      - "us-central1-docker.pkg.dev/observiq-containers/collector/observiq-otel-collector-amd64:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "us-central1-docker.pkg.dev/observiq-containers/collector/observiq-otel-collector-amd64:{{ .Major }}.{{ .Minor }}"
      - "us-central1-docker.pkg.dev/observiq-containers/collector/observiq-otel-collector-amd64:{{ .Major }}"
    dockerfile: ./docker/Dockerfile.ubuntu
    use: buildx
    build_flag_templates:
      - "--label=created={{.Date}}"
      - "--label=title={{.ProjectName}}"
      - "--label=revision={{.FullCommit}}"
      - "--label=version={{.Version}}"
      - "--platform=linux/amd64"
    extra_files:
      - plugins
      - config/example.yaml
      - config/logging.stdout.yaml
      - LICENSE
  - id: ubuntu-arm64
    goos: linux
    goarch: arm64
    ids:
      - collector
    image_templates:
      - "observiq/observiq-otel-collector-arm64:latest"
      - "observiq/observiq-otel-collector-arm64:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "observiq/observiq-otel-collector-arm64:{{ .Major }}.{{ .Minor }}"
      - "observiq/observiq-otel-collector-arm64:{{ .Major }}"
      - "ghcr.io/observiq/observiq-otel-collector-arm64:latest"
      - "ghcr.io/observiq/observiq-otel-collector-arm64:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "ghcr.io/observiq/observiq-otel-collector-arm64:{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/observiq/observiq-otel-collector-arm64:{{ .Major }}"
      - "us-central1-docker.pkg.dev/observiq-containers/collector/observiq-otel-collector-arm64:latest"
      - "us-central1-docker.pkg.dev/observiq-containers/collector/observiq-otel-collector-arm64:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "us-central1-docker.pkg.dev/observiq-containers/collector/observiq-otel-collector-arm64:{{ .Major }}.{{ .Minor }}"
      - "us-central1-docker.pkg.dev/observiq-containers/collector/observiq-otel-collector-arm64:{{ .Major }}"
    dockerfile: ./docker/Dockerfile.ubuntu
    use: buildx
    build_flag_templates:
      - "--label=created={{.Date}}"
      - "--label=title={{.ProjectName}}"
      - "--label=revision={{.FullCommit}}"
      - "--label=version={{.Version}}"
      - "--platform=linux/arm64"
    extra_files:
      - plugins
      - config/example.yaml
      - config/logging.stdout.yaml
      - LICENSE

  - id: ubi8-amd64
    goos: linux
    goarch: amd64
    ids:
      - collector
    image_templates:
      - "observiq/observiq-otel-collector-amd64:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-ubi8"
      - "ghcr.io/observiq/observiq-otel-collector-amd64:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-ubi8"
      - "us-central1-docker.pkg.dev/observiq-containers/collector/observiq-otel-collector-amd64:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-ubi8"
    dockerfile: ./docker/Dockerfile.ubi8
    use: buildx
    build_flag_templates:
      - "--label=created={{.Date}}"
      - "--label=title={{.ProjectName}}"
      - "--label=revision={{.FullCommit}}"
      - "--label=version={{.Version}}"
      - "--platform=linux/amd64"
    extra_files:
      - plugins
      - config/example.yaml
      - config/logging.stdout.yaml
      - LICENSE
  - id: ubi8-arm64
    goos: linux
    goarch: arm64
    ids:
      - collector
    image_templates:
      - "observiq/observiq-otel-collector-arm64:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-ubi8"
      - "ghcr.io/observiq/observiq-otel-collector-arm64:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-ubi8"
      - "us-central1-docker.pkg.dev/observiq-containers/collector/observiq-otel-collector-arm64:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-ubi8"
    dockerfile: ./docker/Dockerfile.ubi8
    use: buildx
    build_flag_templates:
      - "--label=created={{.Date}}"
      - "--label=title={{.ProjectName}}"
      - "--label=revision={{.FullCommit}}"
      - "--label=version={{.Version}}"
      - "--platform=linux/arm64"
    extra_files:
      - plugins
      - config/example.yaml
      - config/logging.stdout.yaml
      - LICENSE

docker_manifests:
  - name_template: "observiq/observiq-otel-collector:latest"
    image_templates:
      - "observiq/observiq-otel-collector-amd64:latest"
      - "observiq/observiq-otel-collector-arm64:latest"
    skip_push: false
  - name_template: "observiq/observiq-otel-collector:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    image_templates:
      - "observiq/observiq-otel-collector-amd64:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "observiq/observiq-otel-collector-arm64:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    skip_push: false
  - name_template: "observiq/observiq-otel-collector:{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "observiq/observiq-otel-collector-amd64:{{ .Major }}.{{ .Minor }}"
      - "observiq/observiq-otel-collector-arm64:{{ .Major }}.{{ .Minor }}"
    skip_push: false
  - name_template: "observiq/observiq-otel-collector:{{ .Major }}"
    image_templates:
      - "observiq/observiq-otel-collector-amd64:{{ .Major }}"
      - "observiq/observiq-otel-collector-arm64:{{ .Major }}"
    skip_push: false
  - name_template: "observiq/observiq-otel-collector:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-ubi8"
    image_templates:
      - "observiq/observiq-otel-collector-amd64:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-ubi8"
      - "observiq/observiq-otel-collector-arm64:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-ubi8"
    skip_push: false
  - name_template: "ghcr.io/observiq/observiq-otel-collector:latest"
    image_templates:
      - "ghcr.io/observiq/observiq-otel-collector-amd64:latest"
      - "ghcr.io/observiq/observiq-otel-collector-arm64:latest"
    skip_push: false
  - name_template: "ghcr.io/observiq/observiq-otel-collector:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    image_templates:
      - "ghcr.io/observiq/observiq-otel-collector-amd64:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "ghcr.io/observiq/observiq-otel-collector-arm64:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    skip_push: false
  - name_template: "ghcr.io/observiq/observiq-otel-collector:{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/observiq/observiq-otel-collector-amd64:{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/observiq/observiq-otel-collector-arm64:{{ .Major }}.{{ .Minor }}"
    skip_push: false
  - name_template: "ghcr.io/observiq/observiq-otel-collector:{{ .Major }}"
    image_templates:
      - "ghcr.io/observiq/observiq-otel-collector-amd64:{{ .Major }}"
      - "ghcr.io/observiq/observiq-otel-collector-arm64:{{ .Major }}"
    skip_push: false
  - name_template: "ghcr.io/observiq/observiq-otel-collector:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-ubi8"
    image_templates:
      - "ghcr.io/observiq/observiq-otel-collector-amd64:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-ubi8"
      - "ghcr.io/observiq/observiq-otel-collector-arm64:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-ubi8"
    skip_push: false
  - name_template: "us-central1-docker.pkg.dev/observiq-containers/collector/observiq-otel-collector:latest"
    image_templates:
      - "us-central1-docker.pkg.dev/observiq-containers/collector/observiq-otel-collector-amd64:latest"
      - "us-central1-docker.pkg.dev/observiq-containers/collector/observiq-otel-collector-arm64:latest"
    skip_push: false
  - name_template: "us-central1-docker.pkg.dev/observiq-containers/collector/observiq-otel-collector:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    image_templates:
      - "us-central1-docker.pkg.dev/observiq-containers/collector/observiq-otel-collector-amd64:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "us-central1-docker.pkg.dev/observiq-containers/collector/observiq-otel-collector-arm64:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    skip_push: false
  - name_template: "us-central1-docker.pkg.dev/observiq-containers/collector/observiq-otel-collector:{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "us-central1-docker.pkg.dev/observiq-containers/collector/observiq-otel-collector-amd64:{{ .Major }}.{{ .Minor }}"
      - "us-central1-docker.pkg.dev/observiq-containers/collector/observiq-otel-collector-arm64:{{ .Major }}.{{ .Minor }}"
    skip_push: false
  - name_template: "us-central1-docker.pkg.dev/observiq-containers/collector/observiq-otel-collector:{{ .Major }}"
    image_templates:
      - "us-central1-docker.pkg.dev/observiq-containers/collector/observiq-otel-collector-amd64:{{ .Major }}"
      - "us-central1-docker.pkg.dev/observiq-containers/collector/observiq-otel-collector-arm64:{{ .Major }}"
    skip_push: false
  - name_template: "us-central1-docker.pkg.dev/observiq-containers/collector/observiq-otel-collector:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-ubi8"
    image_templates:
      - "us-central1-docker.pkg.dev/observiq-containers/collector/observiq-otel-collector-amd64:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-ubi8"
      - "us-central1-docker.pkg.dev/observiq-containers/collector/observiq-otel-collector-arm64:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-ubi8"
    skip_push: false

# https://goreleaser.com/customization/checksum/
checksum:
  name_template: "{{ .ProjectName }}-v{{ .Version }}-SHA256SUMS"
  algorithm: sha256

# https://goreleaser.com/customization/sign/
signs:
  - cmd: cosign
    stdin: "{{ .Env.COSIGN_PWD }}"
    args:
      ["sign-blob", "--key=cosign.key", "--output=${signature}", "${artifact}"]
    artifacts: all

# https://goreleaser.com/customization/release/
release:
  draft: false

  # publish to a prerelease first
  prerelease: "true"
  extra_files:
    - glob: "./observiq-otel-collector*.msi"
    - glob: "./scripts/install/install_unix.sh"
    - glob: "./scripts/install/install_macos.sh"

# https://goreleaser.com/customization/changelog/
changelog:
  skip: false
  use: github
  sort: asc
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug Fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: "Dependencies"
      regexp: "^.*deps[(\\w)]*:+.*$"
      order: 30
    - title: Other
      order: 999
