project_name: observiq-otel-collector

before:
  hooks:
    - make release-prep

# https://goreleaser.com/customization/build/
builds:
  - id: collector
    binary: observiq-otel-collector
    main: ./cmd/collector
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/observiq/observiq-otel-collector/internal/version.version=v{{ .Version }}
      - -X github.com/observiq/observiq-otel-collector/internal/version.gitHash={{ .FullCommit }}
      - -X github.com/observiq/observiq-otel-collector/internal/version.date={{ .Date }}
    no_unique_dist_dir: false

# https://goreleaser.com/customization/archive/
archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    files:
      - LICENSE
      - src: release_deps/opentelemetry-java-contrib-jmx-metrics.jar
        dst: "."
        strip_parent: true
      - src: release_deps/config.yaml
        dst: "."
        strip_parent: true
      - src: release_deps/plugins/*
        dst: plugins
        strip_parent: true

    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - id: collector
    file_name_template: "{{ .PackageName }}_{{ .Os }}_{{ .Arch }}"
    package_name: observiq-otel-collector
    vendor: observIQ, Inc
    maintainer: observIQ <support@observiq.com>
    description: observIQ's distribution of the OpenTelemetry collector
    homepage: https://github.com/observIQ/observiq-otel-collector
    license: Apache 2.0
    formats:
      - rpm
      - deb
    bindir: /opt/observiq-otel-collector
    contents:
      - dst: /opt/observiq-otel-collector
        type: dir
        file_info:
          mode: 0755
          owner: observiq-otel-collector
          group: observiq-otel-collector
      - src: release_deps/config.yaml
        dst: /opt/observiq-otel-collector/config.yaml
        file_info:
          mode: 0640
          owner: observiq-otel-collector
          group: observiq-otel-collector
      - src: LICENSE
        dst: /opt/observiq-otel-collector/LICENSE
        file_info:
          mode: 0644
          owner: observiq-otel-collector
          group: observiq-otel-collector
        type: config|noreplace
      - src: release_deps/opentelemetry-java-contrib-jmx-metrics.jar
        dst: /opt/opentelemetry-java-contrib-jmx-metrics.jar
        file_info:
          mode: 0755
          owner: observiq-otel-collector
          group: observiq-otel-collector
      - dst: /opt/observiq-otel-collector/plugins
        type: dir
        file_info:
          mode: 0750 # restrict plugins to owner / group only
          owner: observiq-otel-collector
          group: observiq-otel-collector
      # Note: plugins owner/group/mode is set in the post-install script
      # Attempting to set the permissions here results in the following error:
      # nfpm failed: cannot write header of release_deps/plugins/amazon_eks.yaml to data.tar.gz: archive/tar: missed writing 1736 bytes
      - src: release_deps/plugins/*
        dst: /opt/observiq-otel-collector/plugins
    scripts:
      preinstall: "./scripts/package/preinstall.sh"
      postinstall: ./scripts/package/postinstall.sh
# https://goreleaser.com/customization/checksum/
checksum:
  name_template: "{{ .ProjectName }}-v{{ .Version }}-SHA256SUMS"
  algorithm: sha256

# https://goreleaser.com/customization/sign/
signs:
  - cmd: cosign
    stdin: "{{ .Env.COSIGN_PWD }}"
    args:
      ["sign-blob", "--key=cosign.key", "--output=${signature}", "${artifact}"]
    artifacts: all

# https://goreleaser.com/customization/release/
release:
  draft: false
  extra_files:
    - glob: "./observiq-otel-collector*.msi"
    - glob: "./scripts/install/install_unix.sh"

# https://goreleaser.com/customization/changelog/
changelog:
  skip: false
  use: github
  sort: asc
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug Fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: "Dependencies"
      regexp: "^.*deps[(\\w)]*:+.*$"
      order: 30
    - title: Other
      order: 999

# https://goreleaser.com/customization/homebrew/
brews:
  - name: observiq-otel-collector
    tap:
      owner: observIQ
      name: homebrew-observiq-otel-collector
      branch: main
    download_strategy: CurlDownloadStrategy
    folder: Formula
    url_template: https://github.com/observIQ/observiq-otel-collector/releases/download/{{ .Tag }}/{{ .ArtifactName }}
    commit_author:
      name: observiq
      email: support@observiq.com
    homepage: "https://github.com/observIQ/observiq-otel-collector"
    license: "Apache 2.0"
    caveats: |
      ****************************************************************
      After installation please run the following to finish setup:

        # Default location for the opentelemetry-java-contrib-jmx-metrics.jar
        sudo cp #{lib}/opentelemetry-java-contrib-jmx-metrics.jar /opt/

      The configuration file that is run by the service is located at #{prefix}/config.yaml.

      If you are configuring a logreceiver the plugin directory is located at #{prefix}/plugins.
      ****************************************************************

      ****************************************************************
      Below are services commands to run to manage the collector service.
      If you wish to run the collector at boot prefix these commands with sudo
      otherwise the service will run at login.

      To start the collector service run:

        brew services start observiq/observiq-otel-collector/observiq-otel-collector

      To stop the collector service run:

        brew services stop observiq/observiq-otel-collector/observiq-otel-collector

      To restart the collector service run:

        brew services restart observiq/observiq-otel-collector/observiq-otel-collector
      ****************************************************************

      ****************************************************************
      To uninstall the collector and its dependencies run the following commands:

          brew services stop observiq/observiq-otel-collector/observiq-otel-collector
          brew uninstall observiq/observiq-otel-collector/observiq-otel-collector
          sudo rm /opt/opentelemetry-java-contrib-jmx-metrics.jar

      ****************************************************************
    install: |
      bin.install "observiq-otel-collector"
      prefix.install "LICENSE", "config.yaml"
      prefix.install Dir["plugins"]
      lib.install "opentelemetry-java-contrib-jmx-metrics.jar"
    plist: |
      <?xml version="1.0" encoding="UTF-8"?>
      <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
      <plist version="1.0">
        <dict>

          <key>Label</key>
          <string>com.observiq.collector</string>

          <key>ProgramArguments</key>
          <array>
            <string>#{bin}/observiq-otel-collector</string>
            <string>--config</string>
            <string>#{prefix}/config.yaml</string>
          </array>

          <key>RunAtLoad</key>
          <true/>

          <key>StandardErrorPath</key>
          <string>/tmp/observiq-otel-collector.log</string>

          <key>StandardOutPath</key>
          <string>/tmp/observiq-otel-collector.log</string>
        </dict>
      </plist>
    # For local testing
    # skip_upload: "true"
