receivers:
  m365:
    tenant_id: b243371b-5514-4951-840f-152d525b6555
    client_id: 0b110766-c91d-4fe5-bac5-14a16ce3c351
    client_secret: FZu8Q~gFWqIo_vo8tE36TYsymPGk9VfWvTlS7b-I

exporters:
  file/no_rotation:
    path: ./foo


service:
  pipelines:
    metrics:
      level: debug
      receivers: [m365]
      exporters: [file/no_rotation]