// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	rollback "github.com/observiq/observiq-otel-collector/updater/internal/rollback"
	mock "github.com/stretchr/testify/mock"
)

// Installer is an autogenerated mock type for the Installer type
type Installer struct {
	mock.Mock
}

// Install provides a mock function with given fields: _a0
func (_m *Installer) Install(_a0 rollback.Rollbacker) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(rollback.Rollbacker) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewInstaller interface {
	mock.TestingT
	Cleanup(func())
}

// NewInstaller creates a new instance of Installer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewInstaller(t mockConstructorTestingTNewInstaller) *Installer {
	mock := &Installer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
