receivers:
  mongodb:
    hosts:
      - endpoint: 127.0.0.1:27017
    collection_interval: 60s
    # disable TLS
    tls:
      insecure: true

exporters:
  googlecloud:

service:
  pipelines:
    metrics:
      receivers:
      - mongodb
      exporters:
      - googlecloud
