// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("bindplane")
	ScopeName = "github.com/observiq/bindplane-agent/extension/bindplaneextension"
)

const (
	ExtensionStability = component.StabilityLevelAlpha
)
