receivers:
  redis:
    endpoint: "localhost:6379"
    collection_interval: 60s

processors:
  resourcedetection:
    detectors: ["system"]
    system:
      hostname_sources: ["os"]

  batch:

exporters:
  otlp:
    endpoint: https://otlp.nr-data.net:443
    headers:
      api-key: 00000-00000-00000
    tls:
      insecure: false

service:
  pipelines:
    metrics:
      receivers:
      - redis
      processors:
      - resourcedetection
      - batch
      exporters:
      - otlp
