receivers:
  prometheus:
    config:
      scrape_configs:
      - job_name: 'cadvisor'
        scrape_interval: 60s
        static_configs:
        - targets:
          - cadvisor:8080

processors:
  # Detect the running containers hostname
  resourcedetection:
    detectors: ["system"]
    system:
      hostname_sources: ["os"]

  # Copy host.name to cadvisor.collector_hostname and then
  # remove the original. Google will map to "generic_task",
  # which drops host.name. We need to preserve the collector's
  # hostname in order to guarantee uniqueness.
  resource:
    attributes:
    - key: cadvisor.collector_hostname
      from_attribute: host.name
      action: insert
    - key: host.name
      action: delete

exporters: 
  googlecloud:
    metric:
      prefix: workload.googleapis.com/cadvisor
      resource_filters:
        - prefix: cadvisor

service:
  pipelines:
    metrics:
      receivers:
      - prometheus
      processors:
      - resourcedetection
      - resource
      exporters:
      - googlecloud
