// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("http")
	ScopeName = "github.com/observiq/bindplane-agent/receiver/httpreceiver"
)

const (
	LogsStability = component.StabilityLevelAlpha
)
