// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("awss3rehydration")
	ScopeName = "github.com/observiq/bindplane-otel-collector/receiver/awss3rehydrationreceiver"
)

const (
	MetricsStability = component.StabilityLevelAlpha
	LogsStability    = component.StabilityLevelAlpha
	TracesStability  = component.StabilityLevelAlpha
)
