receivers:
  iis:
    collection_interval: 60s

processors:

exporters:
  googlecloud:

service:
  pipelines:
    metrics:
      receivers:
      - iis
      processors:
      exporters:
      - googlecloud
