receivers:
  postgresql:
    endpoint: localhost:5432
    #username: $POSTGRESQL_USERNAME
    #password: $POSTGRESQL_PASSWORD
    collection_interval: 60s
    # TLS is enabled by default, this disables it.
    tls:
      insecure: true

exporters:
  googlecloud:

service:
  pipelines:
    metrics:
      receivers:
      - postgresql
      exporters:
      - googlecloud
