receivers:
  jmx:
    jar_path: /opt/opentelemetry-java-contrib-jmx-metrics.jar
    endpoint: localhost:8005
    target_system: hadoop,jvm
    collection_interval: 60s
    resource_attributes:
      hadoop.endpoint: localhost:8004

exporters: 
  googlecloud:
    metric:
      resource_filters:
        - prefix: hadoop

service:
  pipelines:
    metrics:
      receivers:
      - jmx
      exporters:
      - googlecloud
