# Copyright  observIQ, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# JMX stage downloads the opentelemetry-jmx-metrics.jar used by JMX receivers
#
FROM curlimages/curl:7.82.0 as jmxjar
ARG JMX_JAR_VERSION=v1.15.0
USER root
RUN curl -L \
    --output /opentelemetry-java-contrib-jmx-metrics.jar \
    "https://github.com/open-telemetry/opentelemetry-java-contrib/releases/download/${JMX_JAR_VERSION}/opentelemetry-jmx-metrics.jar"


# eclipse-temurn stage provides the Java runtime used by JMX receivers.
# It is a replacement for the openjdk image, which is considered deprecated.
#
FROM eclipse-temurin:8-jdk as jdk


# Final Stage
#
FROM ubuntu:22.04
WORKDIR /

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        --no-install-recommends \
        systemd tzdata ca-certificates && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN adduser \
    --disabled-password \
    --gecos "" \
    --home /etc/otel \
    --no-create-home \
    --uid 10005 \
    --shell /sbin/nologin \
    otel

RUN mkdir \
    /etc/otel \
    /etc/otel/storage \
    && chown -R otel:otel /etc/otel \
    && chmod 0750 /etc/otel/storage
ENV OIQ_OTEL_COLLECTOR_HOME=/etc/otel
ENV OIQ_OTEL_COLLECTOR_STORAGE=/etc/otel/storage

ENV JAVA_HOME=/opt/java/openjdk
COPY --from=jdk $JAVA_HOME $JAVA_HOME
ENV PATH="${JAVA_HOME}/bin:${PATH}"

RUN mkdir /licenses
COPY LICENSE /licenses/observiq-otel-collector.license

COPY observiq-otel-collector /collector/observiq-otel-collector
COPY --from=jmxjar /opentelemetry-java-contrib-jmx-metrics.jar /opt/opentelemetry-java-contrib-jmx-metrics.jar
COPY plugins /etc/otel/plugins

COPY config/logging.stdout.yaml /etc/otel/logging.yaml

# Default config allows the agent to run without an injected config, which is required
# when connecting to an OpAMP platform.
COPY config/example.yaml /etc/otel/config.yaml

RUN chown otel:otel \
    /etc/otel/config.yaml \
    /etc/otel/logging.yaml

RUN chmod 0600 \
    /etc/otel/config.yaml \
    /etc/otel/logging.yaml

USER otel
WORKDIR /etc/otel

# User should mount /etc/otel/config.yaml at runtime using docker volumes / k8s configmap unless
# connecting to an OpAMP platform.
ENTRYPOINT [ "/collector/observiq-otel-collector" ]
