# Copyright  observIQ, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# eclipse-temurn stage provides the Java runtime used by JMX receivers.
# It is a replacement for the openjdk image, which is considered deprecated.
#
FROM eclipse-temurin:8-jdk as jdk


# Final Stage
#
FROM registry.access.redhat.com/ubi8:8.7
WORKDIR /

RUN dnf install -y \
        systemd tzdata ca-certificates && \
  	dnf clean all && \
  	rm -rf /var/cache/yum

RUN groupadd --gid 10005 otel && \
    adduser \
    --system \
    --home /etc/otel \
    --no-create-home \
    --uid 10005 \
    --gid otel \
    --shell /sbin/nologin \
    otel

RUN mkdir \
    /etc/otel \
    /etc/otel/storage \
    && chown -R otel:otel /etc/otel \
    && chmod 0750 /etc/otel/storage
ENV OIQ_OTEL_COLLECTOR_HOME=/etc/otel
ENV OIQ_OTEL_COLLECTOR_STORAGE=/etc/otel/storage

ENV JAVA_HOME=/opt/java/openjdk
COPY --from=jdk $JAVA_HOME $JAVA_HOME
ENV PATH="${JAVA_HOME}/bin:${PATH}"

RUN mkdir /licenses
COPY LICENSE /licenses/bindplane-otel-collector.license

COPY release_deps/VERSION.txt /etc/otel/VERSION.txt

COPY bindplane-otel-collector /collector/bindplane-otel-collector
COPY opampsupervisor /collector/opampsupervisor

COPY release_deps/opentelemetry-java-contrib-jmx-metrics.jar /opt/bindplane-otel-collector/opentelemetry-java-contrib-jmx-metrics.jar
COPY release_deps/plugins /etc/otel/plugins

USER otel
WORKDIR /etc/otel

ENTRYPOINT [ "/collector/opampsupervisor", "--config", "/etc/otel/supervisor.yaml" ]
