# Alpine is used to stage files and directories that are
# copied into the scratch image. It is also used to create
# /etc/passwd and /etc/group files for the otel user. Lastly,
# Alpine is used to retrieve the CA certificates.
FROM alpine as stage

RUN addgroup -S -g 10005 otel && adduser -S -u 10005 -G otel otel

RUN apk update && apk add --no-cache ca-certificates

RUN mkdir /licenses
COPY LICENSE /licenses/observiq-otel-collector.license

COPY release_deps/VERSION.txt /etc/otel/VERSION.txt

COPY release_deps/plugins /etc/otel/plugins
COPY config/logging.stdout.yaml /etc/otel/logging.yaml
COPY release_deps/config.yaml /etc/otel/config.yaml

# Scratch images contain nothing by default. The built image
# will contain only what was copied into it. This means it
# does not contain utilities like ls, cat, or even a shell.
# Care must be taken to ensure that the built image contains
# the required permissions and ca-certificate files.
FROM scratch

COPY --from=stage /etc/passwd /etc/passwd
COPY --from=stage /etc/group /etc/group
COPY --from=stage /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=stage --chown=otel:otel /licenses /licenses
COPY --from=stage --chown=otel:otel /etc/otel /etc/otel

COPY observiq-otel-collector /collector/observiq-otel-collector

USER otel
WORKDIR /etc/otel
ENTRYPOINT ["/collector/observiq-otel-collector"]
