#!/bin/sh
# linux-service   Bring up/down linux-service
#
### BEGIN INIT INFO
# Provides:     linux-service
# Default-Start:    2 3 4 5
# Default-Stop:
#Required-Start:
#Required-Stop:
# Should-Start:
# Should-Start:
# Short-Description: Bring up/down linux-service
# Description: Bring up/down fake service
### END INIT INFO

DAEMON=
NAME=linux-service
DESC="linux-service"
PIDFILE=/var/run/linux-service.pid
SCRIPTNAME=/etc/init.d/linux-service

case "$1" in
start)
    echo "Starting linux-service ... $NAME"
    touch "$PIDFILE"
;;
stop)
    echo "Stoping linux-service ... $NAME"
    rm -f "$PIDFILE"
;;
status)
    if [ -f "$PIDFILE" ]; then
        echo "$NAME running with pid file $PIDFILE"
    else
        echo "$NAME is not running"
        exit 3
    fi
;;
*)
    echo "Usage: $0 {start|stop|status}"
    exit 2
    ;;
esac

exit 0
