// Code generated by mockery v2.28.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRunnableService is an autogenerated mock type for the RunnableService type
type MockRunnableService struct {
	mock.Mock
}

// Error provides a mock function with given fields:
func (_m *MockRunnableService) Error() <-chan error {
	ret := _m.Called()

	var r0 <-chan error
	if rf, ok := ret.Get(0).(func() <-chan error); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan error)
		}
	}

	return r0
}

// Start provides a mock function with given fields: ctx
func (_m *MockRunnableService) Start(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Stop provides a mock function with given fields: ctx
func (_m *MockRunnableService) Stop(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockRunnableService interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockRunnableService creates a new instance of MockRunnableService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockRunnableService(t mockConstructorTestingTNewMockRunnableService) *MockRunnableService {
	mock := &MockRunnableService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
