receivers:
  docker_stats:
    collection_interval: 60s

exporters:
  googlecloud:
    metric:
      prefix: workload.googleapis.com/docker
      resource_filters:
        - prefix: container

service:
  pipelines:
    metrics:
      receivers:
      - docker_stats
      exporters:
      - googlecloud
