receivers:
  zookeeper:
    collection_interval: 30s
    endpoint: localhost:2181

processors:
  resourcedetection:
    detectors: ["system"]
    system:
      hostname_sources: ["os"]

  batch:

exporters:
  otlp:
    endpoint: https://otlp.nr-data.net:443
    headers:
      api-key: 00000-00000-00000
    tls:
      insecure: false

service:
  pipelines:
    metrics:
      receivers:
      - zookeeper
      processors:
      - resourcedetection
      - batch
      exporters:
      - otlp
