# This manifest is a combination of the upstream opentelemetry-collector-contrib manifest & components unique to observIQ's distribution.
# https://github.com/open-telemetry/opentelemetry-collector-releases/blob/main/distributions/otelcol-contrib/manifest.yaml
dist:
  module: github.com/observiq/bindplane-otel-collector
  name: bindplane-otel-collector
  description: ObservIQ's custom distro for OpenTelemetry Collector
  version: "v2.0.0"
  output_path: ./builder
conf_resolver:
  default_uri_scheme: "env"
extensions:
  - gomod: go.opentelemetry.io/collector/extension/zpagesextension v0.114.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/ackextension v0.114.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/asapauthextension v0.114.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/awsproxy v0.114.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/basicauthextension v0.114.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/bearertokenauthextension v0.114.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/encoding/jaegerencodingextension v0.114.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/encoding/otlpencodingextension v0.114.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/encoding/zipkinencodingextension v0.114.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/headerssetterextension v0.114.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.114.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/httpforwarderextension v0.114.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/jaegerremotesampling v0.114.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/oauth2clientauthextension v0.114.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/observer/dockerobserver v0.114.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/observer/ecsobserver v0.114.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/observer/ecstaskobserver v0.114.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/observer/hostobserver v0.114.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/observer/k8sobserver v0.114.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/oidcauthextension v0.114.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/opampextension v0.114.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/pprofextension v0.114.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/sigv4authextension v0.114.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage v0.114.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/dbstorage v0.114.0
  - gomod: github.com/observiq/bindplane-otel-collector/extension/bindplaneextension v1.66.0
    path: "./extension/bindplaneextension"
exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.114.0
  - gomod: go.opentelemetry.io/collector/exporter/nopexporter v0.114.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.114.0
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.114.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/fileexporter v0.114.0
processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.114.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/attributesprocessor v0.114.0
  - gomod: github.com/observiq/bindplane-otel-collector/processor/snapshotprocessor v1.66.0
    path: "./processor/snapshotprocessor"
  - gomod: github.com/observiq/bindplane-otel-collector/processor/throughputmeasurementprocessor v1.66.0
    path: "./processor/throughputmeasurementprocessor"
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor v0.114.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbyattrsprocessor v0.114.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbytraceprocessor v0.114.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor v0.114.0
receivers:
  - gomod: go.opentelemetry.io/collector/receiver/nopreceiver v0.114.0
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.114.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/collectdreceiver v0.114.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver v0.114.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver v0.114.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jmxreceiver v0.114.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/saphanareceiver v0.114.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/sapmreceiver v0.114.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/statsdreceiver v0.114.0
  - gomod: github.com/observiq/bindplane-otel-collector/receiver/pluginreceiver v1.66.0
    path: "./receiver/pluginreceiver"
  - gomod: github.com/observiq/bindplane-otel-collector/receiver/routereceiver v1.66.0
    path: "./receiver/routereceiver"
  - gomod: github.com/observiq/bindplane-otel-collector/receiver/telemetrygeneratorreceiver v1.66.0
    path: "./receiver/telemetrygeneratorreceiver"
connectors:
  - gomod: go.opentelemetry.io/collector/connector/forwardconnector v0.114.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/connector/countconnector v0.114.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/connector/datadogconnector v0.114.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/connector/exceptionsconnector v0.114.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/connector/grafanacloudconnector v0.114.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/connector/roundrobinconnector v0.114.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/connector/routingconnector v0.114.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/connector/servicegraphconnector v0.114.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/connector/spanmetricsconnector v0.114.0
providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v0.114.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v0.114.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v0.114.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v0.114.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v0.114.0
# When adding a replace, add a comment before it to document why it's needed and when it can be removed
replaces:
  # See https://github.com/google/gnostic/issues/262
  - github.com/googleapis/gnostic v0.5.6 => github.com/googleapis/gnostic v0.5.5
  # See https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12322#issuecomment-1185029670
  - github.com/docker/go-connections v0.4.1-0.20210727194412-58542c764a11 => github.com/docker/go-connections v0.4.0
  # see https://github.com/mattn/go-ieproxy/issues/45
  - github.com/mattn/go-ieproxy => github.com/mattn/go-ieproxy v0.0.1
  # see https://github.com/openshift/api/pull/1515
  - github.com/openshift/api => github.com/openshift/api v0.0.0-20230726162818-81f778f3b3ec
  # replace for datapointcountprocessor
  - github.com/observiq/bindplane-otel-collector/receiver/routereceiver => ../receiver/routereceiver
  # replace statements for internal imports
  - github.com/observiq/bindplane-otel-collector/internal/expr => ../internal/expr
  - github.com/observiq/bindplane-otel-collector/internal/counter => ../internal/counter
  - github.com/observiq/bindplane-otel-collector/internal/report => ../internal/report
  - github.com/observiq/bindplane-otel-collector/internal/testutils => ../internal/testutils
  - github.com/observiq/bindplane-otel-collector/internal/rehydration => ../internal/rehydration
  - github.com/observiq/bindplane-otel-collector/internal/version => ../internal/version
  - github.com/observiq/bindplane-otel-collector/internal/measurements => ../internal/measurements
  # Thrift only updates twice a year if we're lucky, and we don't want to wait 6+ months for
  # https://github.com/apache/thrift/pull/3042
  - github.com/apache/thrift => github.com/apache/thrift v0.21.1-0.20240926171305-90af876c67be
