// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("sapnetweaver")
	ScopeName = "github.com/observiq/bindplane-agent/receiver/sapnetweaverreceiver"
)

const (
	MetricsStability = component.StabilityLevelAlpha
)
