receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
processors:
  anomaly:
    comparison_windows:
      current_window: 1m
      baseline_window: 3m
    deviation_threshold: 90

exporters:
  nop:

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [anomaly]
      exporters: [nop]

