# Super basic configuration sending logs from ~/example.log to a local setup of observIQ
# Run in git root:
# OIQ_API_KEY=<api key> ./build/observiqcol_darwin_amd64 --config config/example-log-to-observiq.yaml
receivers:
  filelog:
    include: 
    - "${HOME}/example.log"

processors:
  batch:
    timeout: 5s
    send_batch_size: 10

exporters:
  observiq:
    api_key: "${OIQ_API_KEY}"
    endpoint: "http://localhost:4017/v1/add"
    timeout: 10s
    agent_id: "67ab1c5f-34b3-482c-ba0d-7db0a17a4e87"
    agent_name: "otel-collector-1"

service:
  pipelines:
    logs:
      receivers: [filelog]
      processors: [batch]
      exporters: [observiq]