# File logging configuration assumes OIQ_OTEL_COLLECTOR_HOME
# is set in the collector's environment. 
output: file
level: info
file:
  filename: "${OIQ_OTEL_COLLECTOR_HOME}/log/collector.log"
  maxbackups: 5
  maxsize: 1
  maxage: 7
