server:
  endpoint: ws://localhost:3001/v1/opamp

capabilities:
  accepts_remote_config: true
  reports_remote_config: true

agent:
  executable: "./bindplane-agent"

storage:
  directory: "./supervisor_storage"
