// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockRollbackableAction is an autogenerated mock type for the RollbackableAction type
type MockRollbackableAction struct {
	mock.Mock
}

// Rollback provides a mock function with given fields:
func (_m *MockRollbackableAction) Rollback() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockRollbackableAction interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockRollbackableAction creates a new instance of MockRollbackableAction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockRollbackableAction(t mockConstructorTestingTNewMockRollbackableAction) *MockRollbackableAction {
	mock := &MockRollbackableAction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
