// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RollbackableAction is an autogenerated mock type for the RollbackableAction type
type RollbackableAction struct {
	mock.Mock
}

// Rollback provides a mock function with given fields:
func (_m *RollbackableAction) Rollback() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewRollbackableAction interface {
	mock.TestingT
	Cleanup(func())
}

// NewRollbackableAction creates a new instance of RollbackableAction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRollbackableAction(t mockConstructorTestingTNewRollbackableAction) *RollbackableAction {
	mock := &RollbackableAction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
