// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	models "github.com/observiq/observiq-otel-collector/receiver/sapnetweaverreceiver/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockWebService is an autogenerated mock type for the MockWebService type
type MockWebService struct {
	mock.Mock
}

// EnqGetLockTable provides a mock function with given fields:
func (_m *MockWebService) EnqGetLockTable() (*models.EnqGetLockTableResponse, error) {
	ret := _m.Called()

	var r0 *models.EnqGetLockTableResponse
	if rf, ok := ret.Get(0).(func() *models.EnqGetLockTableResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.EnqGetLockTableResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAlertTree provides a mock function with given fields:
func (_m *MockWebService) GetAlertTree() (*models.GetAlertTreeResponse, error) {
	ret := _m.Called()

	var r0 *models.GetAlertTreeResponse
	if rf, ok := ret.Get(0).(func() *models.GetAlertTreeResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.GetAlertTreeResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetInstanceProperties provides a mock function with given fields:
func (_m *MockWebService) GetInstanceProperties() (*models.GetInstancePropertiesResponse, error) {
	ret := _m.Called()

	var r0 *models.GetInstancePropertiesResponse
	if rf, ok := ret.Get(0).(func() *models.GetInstancePropertiesResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.GetInstancePropertiesResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTnewMockWebService interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockWebService creates a new instance of MockWebService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockWebService(t mockConstructorTestingTnewMockWebService) *MockWebService {
	mock := &MockWebService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
