receivers:
  elasticsearch:
    nodes: ["_local"]
    endpoint: http://localhost:9200
    collection_interval: 60s

exporters:
  googlecloud:
    metric:
      prefix: workload.googleapis.com/elastic
      resource_filters:
        - prefix: elasticsearch

service:
  pipelines:
    metrics:
      receivers:
      - elasticsearch
      exporters:
      - googlecloud
