receivers:
  elasticsearch:
    nodes: ["_local"]
    endpoint: http://localhost:9200
    collection_interval: 60s

processors:
  # Resourcedetection is used to add a unique (host.name)
  # to the metric resource(s), allowing users to filter
  # between multiple agent systems.
  resourcedetection:
    detectors: ["system"]
    system:
      hostname_sources: ["os"]

  resource:
    attributes:
    - key: location
      value: global
      action: upsert

  resourceattributetransposer:
    operations:
      - from: host.name
        to: agent
      - from: elasticsearch.cluster.name
        to: cluster_name

  normalizesums:

  batch:

exporters:
  googlecloud:
    retry_on_failure:
      enabled: false
    metric:
      prefix: workload.googleapis.com
    resource_mappings:
      - source_type: ""
        target_type: generic_node
        label_mappings:
          - source_key: elasticsearch.node.name
            target_key: node_id
          - source_key: elasticsearch.node.name
            target_key: namespace
          - source_key: location
            target_key: location

service:
  pipelines:
    metrics:
      receivers:
      - elasticsearch
      processors:
      - resourcedetection
      - resource
      - resourceattributetransposer
      - normalizesums
      - batch
      exporters:
      - googlecloud
