receivers:
  apache:
    collection_interval: 60s
    endpoint: http://localhost:80/server-status?auto
    tls:
      insecure: true

  plugin:
    path: $OIQ_OTEL_COLLECTOR_HOME/plugins/apache_http_logs.yaml
    parameters:
      access_log_path:
        - /var/log/apache2/access.log
      enable_access_log: true
      enable_error_log: true
      error_log_path:
        - /var/log/apache2/error.log
      start_at: end
      timezone: UTC

exporters:
  googlecloud:

service:
  pipelines:
    logs:
      receivers:
        - plugin
      exporters:
        - googlecloud
    metrics:
      receivers:
        - apache
      exporters:
        - googlecloud
