receivers:
  hostmetrics:
    collection_interval: 60s
    scrapers:
      cpu:
      disk:
      load:
      filesystem:
      memory:
      network:
      paging:
      processes:

      # Uncomment "process" and "mute_process_name_error" to enable
      # per process metrics for cpu, memory, and disk.
      # This feature requires root / Administrative privileges.
      #process:
      #  mute_process_name_error: true


processors:
  # Resourcedetection is used to add a unique (host.name)
  # to the metric resource(s), allowing users to filter
  # between multiple systems.
  resourcedetection:
    detectors: ["system"]
    system:
      hostname_sources: ["os"]

  normalizesums:

  batch:

exporters: 
  # The prometheus exporter exposes a TCP port on the collector, that is then scraped
  # by your Google Prometheus server.
  prometheus:
    # The endpoint of the agent, that will be scraped by
    # your prometheus server.
    endpoint: "127.0.0.1:9000"
    # copies resource attributes to metric labels
    resource_to_telemetry_conversion:
      enabled: true

service:
  pipelines:
    metrics:
      receivers:
      - hostmetrics
      processors:
      - resourcedetection
      - normalizesums
      - batch
      exporters:
      - prometheus
