receivers:
  rabbitmq:
    endpoint: http://localhost:15672
    collection_interval: 60s
    # From environment. See README.md.
    username: $RABBITMQ_USERNAME
    password: $RABBITMQ_PASSWORD

processors:
  # Resourcedetection is used to add a unique (host.name)
  # to the metric resource(s), allowing users to filter
  # between multiple agent systems.
  resourcedetection:
    detectors: ["system"]
    system:
      hostname_sources: ["os"]

  resource:
    attributes:
    - key: location
      value: global
      action: upsert

  resourceattributetransposer:
    operations:
      # Rabbitmq metrics require unique metric labels, otherwise the Google
      # API will reject some metrics as "out of order" / duplicates. This happens
      # when there are multiple rabbitmq instances or multiple vhosts / queues.
      - from: host.name
        to: agent
      - from: rabbitmq.queue.name
        to: queue
      - from: rabbitmq.vhost.name
        to: vhost

  normalizesums:

  batch:

exporters: 
  googlecloud:
    retry_on_failure:
      enabled: false
    metric:
      prefix: workload.googleapis.com
    resource_mappings:
      - source_type: ""
        target_type: generic_node
        label_mappings:
          - source_key: rabbitmq.node.name
            target_key: node_id
          - source_key: rabbitmq.node.name
            target_key: namespace
          - source_key: location
            target_key: location

service:
  pipelines:
    metrics:
      receivers:
      - rabbitmq
      processors:
      - resourcedetection
      - resource
      - resourceattributetransposer
      - normalizesums
      - batch
      exporters:
      - googlecloud
