receivers:
  rabbitmq:
    endpoint: http://localhost:15672
    collection_interval: 60s
    # From environment. See README.md.
    username: $RABBITMQ_USERNAME
    password: $RABBITMQ_PASSWORD

exporters: 
  googlecloud:
    metric:
      resource_filters:
        - prefix: rabbitmq

service:
  pipelines:
    metrics:
      receivers:
      - rabbitmq
      exporters:
      - googlecloud
