receivers:
  elasticsearch:
    nodes: ["_local"]
    endpoint: http://localhost:9200
    collection_interval: 60s

processors:
  batch:

exporters:
  otlp:
    endpoint: https://otlp.nr-data.net:443
    headers:
      api-key: 00000-00000-00000
    tls:
      insecure: false

service:
  pipelines:
    metrics:
      receivers:
      - elasticsearch
      processors:
      - batch
      exporters:
      - otlp
