// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("marshal")
	ScopeName = "github.com/observiq/bindplane-agent/processor/marshalprocessor"
)

const (
	LogsStability = component.StabilityLevelDevelopment
)
