receivers:
  mysql:
    endpoint: localhost:3306
    username: $MYSQL_USERNAME
    password: $MYSQL_PASSWORD
    collection_interval: 60s

exporters:
  googlecloud:

service:
  pipelines:
    metrics:
      receivers:
      - mysql
      exporters:
      - googlecloud
