# Takes a tag name, gives info about the release (title, body, pre-release)
name: "GH Release Info"
description: "Gives info about the release"
inputs:
  repo-name:
    description: 'Repo name (e.g. `owner/repo`)'
    default: ${{ github.repository }}
    required: false
  tag:
    description: 'Tag for the release'
    required: true
  token:
    description: 'Token for making requests to github'
    default: ${{ github.token }}
    required: false
outputs:
  id:
    description: 'Release ID'
    value: ${{ steps.get-info.outputs.id }}
  title:
    description: 'Release title'
    value: ${{ steps.get-info.outputs.title }}
  body:
    description: 'Release body (markdown)'
    value: ${{ steps.get-info.outputs.body }}
  pre-release:
    description: 'Whether or not this release is a pre-release'
    value: ${{ steps.get-info.outputs.pre-release }}
runs:
  using: "composite"
  steps:
    - id: get-info
      run: ${{ github.action_path }}/get-release-info-by-tag.sh ${{ inputs.repo-name }} ${{ inputs.tag }} ${{ inputs.token }}
      shell: bash

      