receivers:
  journald:
    priority: info
    operators:
      - type: add
        field: attributes.log_type
        value: journald

exporters: 
  googlecloud:

service:
  pipelines:
    logs:
      receivers:
      - journald
      exporters:
      - googlecloud
