receivers:
  windowseventlog/application:
    channel: application
    labels:
      log_type: windows_event.application

  windowseventlog/security:
    channel: security
    labels:
      log_type: windows_event.security

  windowseventlog/system:
    channel: system
    labels:
      log_type: windows_event.system

exporters:
  googlecloud:

service:
  pipelines:
    logs:
      receivers:
        - windowseventlog/system
        - windowseventlog/application
        - windowseventlog/security
      exporters:
        - googlecloud
