receivers:
  jmx:
    collection_interval: 30s
    endpoint: localhost:9999
    jar_path: /opt/opentelemetry-java-contrib-jmx-metrics.jar
    target_system: solr
    resource_attributes:
      solr.endpoint: localhost:9999

processors:
  resourcedetection:
    detectors: ["system"]
    system:
      hostname_sources: ["os"]

  batch:

exporters:
  otlp:
    endpoint: https://otlp.nr-data.net:443
    headers:
      api-key: 00000-00000-00000
    tls:
      insecure: false

service:
  pipelines:
    metrics:
      receivers:
      - jmx
      processors:
      - resourcedetection
      - batch
      exporters:
      - otlp
