receivers:
  jmx:
    jar_path: /opt/opentelemetry-java-contrib-jmx-metrics.jar
    endpoint: localhost:9000
    target_system: tomcat,jvm
    collection_interval: 60s
    resource_attributes:
      tomcat.endpoint: localhost:9000

exporters: 
  googlecloud:
    metric:
      resource_filters:
        - prefix: tomcat

service:
  pipelines:
    metrics:
      receivers:
      - jmx
      exporters:
      - googlecloud
