receivers:
  jmx:
    jar_path: /opt/opentelemetry-java-contrib-jmx-metrics.jar
    endpoint: localhost:9000
    target_system: tomcat,jvm
    collection_interval: 60s
    properties:
      otel.resource.attributes: jmx_source=tomcat,jmx_endpoint=localhost:9000

processors:
  resourcedetection:
    detectors: ["system"]
    system:
      hostname_sources: ["os"]

  resourceattributetransposer:
    operations:
      - from: "host.name"
        to: "agent"
      - from: "jmx_source"
        to: "jmx_source"
      - from: "jmx_endpoint"
        to: "jmx_endpoint"

  normalizesums:

  batch:

exporters: 
  googlecloud:
    retry_on_failure:
      enabled: false
    metric:
      prefix: custom.googleapis.com

service:
  pipelines:
    metrics:
      receivers:
      - jmx
      processors:
      - resourcedetection
      - resourceattributetransposer
      - normalizesums
      - batch
      exporters:
      - googlecloud
