receivers:
  mongodbatlas:
    public_key: $MONGODB_ATLAS_PUBLIC_KEY
    private_key: $MONGODB_ATLAS_PRIVATE_KEY
    collection_interval: 5m

processors:
  resourcedetection:
    detectors: ["system"]
    system:
      hostname_sources: ["os"]

  # Copy useful mongodb specific attributes that will otherwise
  # be dropped by the Google exporter.
  resourceattributetransposer:
    operations:
      - from: host.name
        to: agent
      - from: mongodb_atlas.org_name
        to: org_name
      - from: mongodb_atlas.project.name
        to: project
      - from: mongodb_atlas.db.name
        to: database
      - from: mongodb_atlas.process.type_name
        to: process_type

  # Used for Google generic_node mapping.
  resource:
    attributes:
    - key: namespace
      value: "mongodbatlas"
      action: upsert
    - key: location
      value: "global"
      action: upsert

  normalizesums:

  batch:

exporters: 
  googlecloud:
    retry_on_failure:
      enabled: false
    metric:
      prefix: workload.googleapis.com
    resource_mappings:
    - source_type: ""
      target_type: generic_node
      label_mappings:
      - source_key: mongodb_atlas.host.name
        target_key: node_id
      - source_key: location
        target_key: location
      - source_key: namespace
        target_key: namespace

service:
  pipelines:
    metrics:
      receivers:
      - mongodbatlas
      processors:
      - resourcedetection
      - resourceattributetransposer
      - resource
      - normalizesums
      - batch
      exporters:
      - googlecloud
