receivers:
  mongodbatlas:
    public_key: $MONGODB_ATLAS_PUBLIC_KEY
    private_key: $MONGODB_ATLAS_PRIVATE_KEY
    collection_interval: 60s

exporters: 
  googlecloud:
    metric:
      resource_filters:
        - prefix: mongodb_atlas

service:
  pipelines:
    metrics:
      receivers:
      - mongodbatlas
      exporters:
      - googlecloud
