receivers:
  redis:
    endpoint: "localhost:6379"
    collection_interval: 60s

exporters:
  googlecloud:

service:
  pipelines:
    metrics:
      receivers:
      - redis
      exporters:
      - googlecloud
