name: build-msi
on:
  pull_request:

jobs:
  build-msi:
    runs-on: windows-2019
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"
          check-latest: true
      - name: Cache Go Modules
        uses: actions/cache@v2
        with:
          path: |
            %LocalAppData%\go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Build Windows Binary
        run: |
          make build-windows
          cp dist/collector_windows_amd64.exe windows/observiq-collector.exe
      - name: Get Stanza Plugins Ref
        id: plugins
        run: echo "::set-output name=ref::$(Get-Content ./PLUGINS_VERSION)"
      - name: Get JMX Jar Version
        id: jmx-jar
        run: echo "::set-output name=release::$(Get-Content ./JAVA_CONTRIB_VERSION)"
      - name: Checkout Plugins
        uses: actions/checkout@v2
        with:
          repository: observIQ/stanza-plugins
          ref: ${{ steps.plugins.outputs.ref }}
          path: stanza-plugins
      - name: Copy Plugins to MSI Build Directory
        run: cp -r stanza-plugins/plugins windows/
      - name: Copy Example Config
        run: cp config/example.yaml windows/config.yaml
      - name: Download JMX Receiver Jar
        run: curl -f -L -o windows/opentelemetry-java-contrib-jmx-metrics.jar https://github.com/open-telemetry/opentelemetry-java-contrib/releases/download/${{ steps.jmx-jar.outputs.release }}/opentelemetry-jmx-metrics.jar
      # HACK: Copy build directory to C drive to avoid this error, since there must be a relative path from the tempdir that go-msi uses
      # for the MSI to build properly
      - name: Copy Build Dir
        run: |
          cp -r windows C:/build
          echo "C:/build" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      # Installs go-msi and wix.
      - name: Install Build Tools
        run: 	|
          curl -f -L -o go-msi.exe https://github.com/observIQ/go-msi/releases/download/v2.0.0/go-msi.exe
          curl -f -L -o wix310-binaries.zip http://wixtoolset.org/downloads/v3.10.3.3007/wix310-binaries.zip
          unzip wix310-binaries.zip
        working-directory: C:/build
      - name: Get Tag From Environment
        id: get-tag
        run: printf '::set-output name=tag::v0.0.13'
      - name: "Build MSI from Tagged Release"
        run: go-msi.exe make -m observiq-collector.msi --version ${{ steps.get-tag.outputs.tag }} --arch amd64
        working-directory: C:/build
      - name: Install MSI
        run: msiexec.exe /qn /i observiq-collector.msi
        working-directory: C:/build
      - name: Install CINC (Inspec)
        run: . { iwr -useb https://omnitruck.cinc.sh/install.ps1 } | iex; install -project cinc-auditor -version 4
      - name: Run CINC (Inspec) Install Tests
        run: C:/cinc-project/cinc-auditor/bin/cinc-auditor.bat exec install.rb
        working-directory: C:/build/test
      - name: Uninstall MSI
        run: |
          msiexec.exe /qn /x observiq-collector.msi
          sleep 5
        working-directory: C:/build
      - name: Run CINC (Inspec) Uninstall Tests
        run: C:/cinc-project/cinc-auditor/bin/cinc-auditor.bat exec uninstall.rb
        working-directory: C:/build/test
      - name: "Rename MSI to include version tag"
        run: mv observiq-collector.msi observiq-collector-${{ steps.get-tag.outputs.tag }}.msi
        working-directory: C:/build
      - name: "Upload MSI"
        uses: actions/upload-artifact@v2
        with:
          name: observiq-collector-${{ steps.get-tag.outputs.tag }}.msi
          path: C:/build/observiq-collector-${{ steps.get-tag.outputs.tag }}.msi
          # Short lived because Go Releaser will upload the msi to a release (github release, gcs, etc)
          retention-days: 1
