name: check_plugin_docs
on:
  pull_request:

jobs:
  check-plugin-docs:
    runs-on: "ubuntu-20.04"
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
          check-latest: true
      - name: Plugin Doc Generation
        run: make create-plugin-docs
      - name: Check Changed Plugin Docs
        uses: tj-actions/verify-changed-files@v12
        id: verify-changed-files
        with:
          files: |
            docs/plugins
      - name: Verify No Plugin Doc Changes
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: exit 1
