name: check-formatting
on:
  pull_request:

jobs:
  check-fmt:
    runs-on: "ubuntu-20.04"
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"
          check-latest: true
      - name: Install Tools
        run: make install-tools
      - name: Check Formatting
        run: make check-fmt
