name: check-formatting
on:
  pull_request:

jobs:
  check-fmt:
    runs-on: "ubuntu-20.04"
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          check-latest: true
          cache: false
      - name: Install Tools
        run: make install-tools
      - name: Check Formatting
        run: make check-fmt
