name: Gosec
on:
  workflow_dispatch:
  pull_request:

jobs:
  gosec:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          check-latest: true
      - name: Install Tools
        run: make install-tools
      - name: Run Gosec Security Scanner
        run: make gosec
