name: update_homebrew_current
on:
  release:
    # released is triggered when a pre-release is changed to a release see documentation https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#release
    type: [released]

jobs:
  trigger-hombrew-update:
    # Only trigger this if it's not a prerelease
    if: "!github.event.release.prerelease"
    runs-on: "ubuntu-20.04"
    steps:
      # Extract version from release and remove leading 'v'
      - name: Get Release Version
        id: get_version
        run: |
          echo "::set-output name=version::$(echo ${{ github.event.release.tag_name }} | sed 's/v//')"
      # Trigger Action on homebrew repository
      - name: Trigger Homebrew Action
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.ORG_GORELEASER_GITHUB_TOKEN }}
          repository: observIQ/homebrew-observiq-otel-collector
          event-type: upstream_release
          client-payload: '{ "new_version": "${{ steps.get_version.outputs.version }}" }'
