name: misspell
on:
  pull_request:

jobs:
  misspell:
    runs-on: "ubuntu-20.04"
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2
      - name: Run misspell
        run: make misspell
