# Build is responsible for testing builds on all supported platforms.
# It is broken up into three separate jobs with targeted builds so that each OS will
# build in parallel and speed up overall CI time.
name: Build
on:
  pull_request:

jobs:
  setup-tools:
    runs-on: "ubuntu-20.04"
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          check-latest: true
      - name: Cache Tools
        id: tool-cache
        uses: actions/cache@v3
        with:
          path: /home/runner/go/bin
          key: tooling-${{ runner.os }}-${{ hashFiles('./internal/tools/go.sum') }}
      - name: Install Tools
        if: steps.tool-cache.outputs.cache-hit != 'true'
        run: make install-tools

  build_linux:
    runs-on: ubuntu-latest-4-cores
    needs:
      - setup-tools
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          check-latest: true
      - name: Cache Tools
        id: tool-cache
        uses: actions/cache@v3
        with:
          path: /home/runner/go/bin
          key: tooling-${{ runner.os }}-${{ hashFiles('./internal/tools/go.sum') }}
      - name: Install Tools
        if: steps.tool-cache.outputs.cache-hit != 'true'
        run: make install-tools
      - name: Build
        run: make build-linux
      - name: Scan Third Party Dependency Licenses
        run: |
          go install github.com/uw-labs/lichen@v0.1.7
          lichen --config=./license.yaml $(find dist/collector_* dist/updater_*)

  build_darwin:
    runs-on: macos-14
    needs:
      - setup-tools
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          check-latest: true
      - name: Cache Tools
        id: tool-cache
        uses: actions/cache@v3
        with:
          path: /home/runner/go/bin
          key: tooling-${{ runner.os }}-${{ hashFiles('./internal/tools/go.sum') }}
      - name: Install Tools
        if: steps.tool-cache.outputs.cache-hit != 'true'
        run: make install-tools
      - name: Build
        run: make build-darwin
      - name: Scan Third Party Dependency Licenses
        run: |
          go install github.com/uw-labs/lichen@v0.1.7
          lichen --config=./license.yaml $(find dist/collector_* dist/updater_*)
      - name: Get disk usage
        if: always()
        run: |
          df -h
          du -sh

  build_windows:
    runs-on: ubuntu-20.04
    needs:
      - setup-tools
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          check-latest: true
      - name: Cache Tools
        id: tool-cache
        uses: actions/cache@v3
        with:
          path: /home/runner/go/bin
          key: tooling-${{ runner.os }}-${{ hashFiles('./internal/tools/go.sum') }}
      - name: Install Tools
        if: steps.tool-cache.outputs.cache-hit != 'true'
        run: make install-tools
      - name: Build
        run: make build-windows
      - name: Scan Third Party Dependency Licenses
        run: |
          go install github.com/uw-labs/lichen@v0.1.7
          lichen --config=./license.yaml dist/collector_windows_amd64.exe dist/updater_windows_amd64.exe
