// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/confmap/confmaptest"
)

func TestMetricsBuilderConfig(t *testing.T) {
	tests := []struct {
		name string
		want MetricsBuilderConfig
	}{
		{
			name: "default",
			want: DefaultMetricsBuilderConfig(),
		},
		{
			name: "all_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					M365OnedriveFilesActiveCount:    MetricConfig{Enabled: true},
					M365OnedriveFilesCount:          MetricConfig{Enabled: true},
					M365OnedriveUserActivityCount:   MetricConfig{Enabled: true},
					M365OutlookAppUserCount:         MetricConfig{Enabled: true},
					M365OutlookEmailActivityCount:   MetricConfig{Enabled: true},
					M365OutlookMailboxesActiveCount: MetricConfig{Enabled: true},
					M365OutlookQuotaStatusCount:     MetricConfig{Enabled: true},
					M365OutlookStorageUsed:          MetricConfig{Enabled: true},
					M365SharepointFilesActiveCount:  MetricConfig{Enabled: true},
					M365SharepointFilesCount:        MetricConfig{Enabled: true},
					M365SharepointPagesUniqueCount:  MetricConfig{Enabled: true},
					M365SharepointPagesViewedCount:  MetricConfig{Enabled: true},
					M365SharepointSiteStorageUsed:   MetricConfig{Enabled: true},
					M365SharepointSitesActiveCount:  MetricConfig{Enabled: true},
					M365TeamsCallsCount:             MetricConfig{Enabled: true},
					M365TeamsDeviceUsageUsers:       MetricConfig{Enabled: true},
					M365TeamsMeetingsCount:          MetricConfig{Enabled: true},
					M365TeamsMessagesPrivateCount:   MetricConfig{Enabled: true},
					M365TeamsMessagesTeamCount:      MetricConfig{Enabled: true},
				},
				ResourceAttributes: ResourceAttributesConfig{
					M365TenantID: ResourceAttributeConfig{Enabled: true},
				},
			},
		},
		{
			name: "none_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					M365OnedriveFilesActiveCount:    MetricConfig{Enabled: false},
					M365OnedriveFilesCount:          MetricConfig{Enabled: false},
					M365OnedriveUserActivityCount:   MetricConfig{Enabled: false},
					M365OutlookAppUserCount:         MetricConfig{Enabled: false},
					M365OutlookEmailActivityCount:   MetricConfig{Enabled: false},
					M365OutlookMailboxesActiveCount: MetricConfig{Enabled: false},
					M365OutlookQuotaStatusCount:     MetricConfig{Enabled: false},
					M365OutlookStorageUsed:          MetricConfig{Enabled: false},
					M365SharepointFilesActiveCount:  MetricConfig{Enabled: false},
					M365SharepointFilesCount:        MetricConfig{Enabled: false},
					M365SharepointPagesUniqueCount:  MetricConfig{Enabled: false},
					M365SharepointPagesViewedCount:  MetricConfig{Enabled: false},
					M365SharepointSiteStorageUsed:   MetricConfig{Enabled: false},
					M365SharepointSitesActiveCount:  MetricConfig{Enabled: false},
					M365TeamsCallsCount:             MetricConfig{Enabled: false},
					M365TeamsDeviceUsageUsers:       MetricConfig{Enabled: false},
					M365TeamsMeetingsCount:          MetricConfig{Enabled: false},
					M365TeamsMessagesPrivateCount:   MetricConfig{Enabled: false},
					M365TeamsMessagesTeamCount:      MetricConfig{Enabled: false},
				},
				ResourceAttributes: ResourceAttributesConfig{
					M365TenantID: ResourceAttributeConfig{Enabled: false},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadMetricsBuilderConfig(t, tt.name)
			if diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(MetricConfig{}, ResourceAttributeConfig{})); diff != "" {
				t.Errorf("Config mismatch (-expected +actual):\n%s", diff)
			}
		})
	}
}

func loadMetricsBuilderConfig(t *testing.T, name string) MetricsBuilderConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	cfg := DefaultMetricsBuilderConfig()
	require.NoError(t, component.UnmarshalConfig(sub, &cfg))
	return cfg
}

func TestResourceAttributesConfig(t *testing.T) {
	tests := []struct {
		name string
		want ResourceAttributesConfig
	}{
		{
			name: "default",
			want: DefaultResourceAttributesConfig(),
		},
		{
			name: "all_set",
			want: ResourceAttributesConfig{
				M365TenantID: ResourceAttributeConfig{Enabled: true},
			},
		},
		{
			name: "none_set",
			want: ResourceAttributesConfig{
				M365TenantID: ResourceAttributeConfig{Enabled: false},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadResourceAttributesConfig(t, tt.name)
			if diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(ResourceAttributeConfig{})); diff != "" {
				t.Errorf("Config mismatch (-expected +actual):\n%s", diff)
			}
		})
	}
}

func loadResourceAttributesConfig(t *testing.T, name string) ResourceAttributesConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	sub, err = sub.Sub("resource_attributes")
	require.NoError(t, err)
	cfg := DefaultResourceAttributesConfig()
	require.NoError(t, component.UnmarshalConfig(sub, &cfg))
	return cfg
}
