receivers:
  mongodb:
    hosts:
      - endpoint: 127.0.0.1:27017
    collection_interval: 30s
    tls:
      insecure: true

  plugin/mongodb:
    path: $OIQ_OTEL_COLLECTOR_HOME/plugins/mongodb_logs.yaml
    parameters:
      log_paths:
        - /var/log/mongodb/mongod.log
      start_at: end

processors:
  resourcedetection:
    detectors: ["system"]
    system:
      hostname_sources: ["os"]

  batch:

exporters:
  otlp/newrelic:
    endpoint: https://otlp.nr-data.net:443
    headers:
      api-key: 00000-00000-00000
    tls:
      insecure: false

service:
  pipelines:
    metrics:
      receivers:
        - mongodb
      processors:
        - resourcedetection
        - batch
      exporters:
        - otlp/newrelic

    logs:
      receivers:
        - plugin/mongodb
      processors:
        - resourcedetection
        - batch
      exporters:
        - otlp/newrelic
